jenkinsci/support-core-plugin

- src/main/java/com/cloudbees/jenkins/support/impl/BuildQueue.java
- src/test/java/com/cloudbees/jenkins/support/impl/BuildQueueTest.java
The support bundle reporting the build queue would be helpful for debugging any elements that are pending or blocked in the queue.
> [JENKINS-20542] Add summary of current build queue.

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
report PermGen usage (on pre-8 JVM)
detect GC strategy being used
@reviewbybees
> Memory usage

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
> manifest.md: Fix generated date format

- src/main/java/com/cloudbees/jenkins/support/impl/LoadStats.java
- Where possible we include PNG graphs for faster analysis
- Always include a CSV of the raw data
@reviewbybees
> Add load statistics to support bundle.

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
[JENKINS-27669](https://issues.jenkins-ci.org/browse/JENKINS-27669)
@reviewbybees
> [JENKINS-27669] Prevent ClassCircularityError

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
> [JENKINS-28703] Add pinned status for plugins.

- src/main/java/com/cloudbees/jenkins/support/slowrequest/InflightRequest.java
> [JENKINS-28876] Add user-agent information to slow-requests.

- src/main/java/com/cloudbees/jenkins/support/slowrequest/InflightRequest.java
> Add null check before parsing agent header.

- src/main/java/com/cloudbees/jenkins/support/impl/SystemConfiguration.java
This PR adds 2 features:
* add system uptime to see if an outage comes from a system reboot
* add DMI information to see if Jenkins is running on a virtualized server
@reviewbybees
> System conf enhancement

- src/main/java/com/cloudbees/jenkins/support/impl/RootCAs.java
This will only work if there is no password for obtaining the keystore.
> [FIXED JENKINS-21668] Obtain root CA information for java instances

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
> Add Jenkins url information to validate reverse proxy configurations.

- src/main/java/com/cloudbees/jenkins/support/impl/BuildQueue.java
> Check build queue elements to see if the QueueTaskDispatcher is able to

- pom.xml
I would like to be added as a maintainer/developer to the support core plugin.
> Add myself to developers list

- src/main/java/com/cloudbees/jenkins/support/impl/UpdateCenter.java
> Add update center information to support bundle.

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
> JENKINS-32265 - Added "Slave Version" using `Launcher.VERSION` to master node

- src/main/java/com/cloudbees/jenkins/support/slowrequest/InflightRequest.java
> Add the locale of the users browser to a slow request.

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/SupportLogHandler.java
- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/MetricsContent.java
- src/main/java/com/cloudbees/jenkins/support/impl/SmartLogFetcher.java
- src/main/java/com/cloudbees/jenkins/support/timer/FileListCapComponent.java
This is a continuation of https://github.com/jenkinsci/support-core-plugin/pull/40.
@reviewbybees
> Enable FindBugs for the project

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
> JENKINS-34462 - Support core plugin needs to obtain the status of whether CSRF protection is enabled

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
[JENKINS-34719](https://issues.jenkins-ci.org/browse/JENKINS-34719)
@reviewbybees
> [FIXED JENKINS-34719] Pick up and logs that have been refactored into JENKINS_HOME/logs

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
> Use require post annotation.

- src/main/java/com/cloudbees/jenkins/support/impl/BuildQueue.java
> Check if Jenkins is quieting down.

- src/main/java/com/cloudbees/jenkins/support/impl/UpdateCenter.java
> [FIX JENKINS-38572] Only run if async-http-client plugin is installed.

- src/main/java/com/cloudbees/jenkins/support/configfiles/ConfigFileComponent.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponent.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/SecretHandler.java
- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
@reviewbybees 
I also removed some useless catches and imports.
> FIX Javadoc warnings

- src/main/java/com/cloudbees/jenkins/support/api/TemporaryFileContent.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/ConfigFileComponent.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponent.java
[JENKINS-40094](https://issues.jenkins-ci.org/browse/JENKINS-40094)
@reviewbybees
> [FIX JENKINS-40094] Fix global config.xml content

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
@reviewbybees esp. @jglick [who requested an improvement here](https://github.com/jenkinsci/support-core-plugin/pull/92#discussion_r92193085)
> Be defensive against potential listFiles() returning null

- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
> Max file size for agent logs.

- src/main/java/com/cloudbees/jenkins/support/SupportLogFormatter.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/api/CommandOutputContent.java
- src/main/java/com/cloudbees/jenkins/support/api/FileContent.java
- src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
- src/main/java/com/cloudbees/jenkins/support/impl/RemotingDiagnostics.java
- src/main/java/com/cloudbees/jenkins/support/impl/RootCAs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
See https://github.com/jenkinsci/jenkins/pull/1485.
@reviewbybees
> Print stack trace in logical order

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
> Add initialization milestone.

- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
Would I think make problems like that which https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/23 purports to solve more immediately apparent.
@reviewbybees
> [JENKINS-40613] Report a blocked Timer

- pom.xml
> Update to latest plugin parent pom 23

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/resources/com/cloudbees/jenkins/support/Messages.properties
- src/main/resources/com/cloudbees/jenkins/support/SupportAction/index.jelly
List Bundle files to display bundle files.
Then allow to Delete them selecting from UI.
Done thanks to help of @alecharp .
> [JENKINS-35341][JENKINS-35343] Delete selectable Bundle

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/impl/DumpExportTable.java
- src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
- src/main/java/com/cloudbees/jenkins/support/impl/Metrics.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SmartLogFetcher.java
Java elements and bundle structure is not touched for compatibility.
UI and comments are updated.
@reviewbybees
> JENKINS-42512 - "Slave" is replaced with Agent.

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
@reviewbybees 
https://issues.jenkins-ci.org/browse/JENKINS-42169
> [JENKINS-42169] Include task logs in support bundles

- src/main/resources/com/cloudbees/jenkins/support/Messages.properties
[JENKINS-43626] Document that the behavior of the command varies based on CLI protocol.
@reviewbybees @jglick
> [JENKINS-43626] Document the behavior of the command 

- src/main/java/com/cloudbees/jenkins/support/configfiles/SecretHandler.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/SecretHandlerTest.java
https://issues.jenkins-ci.org/browse/JENKINS-41653
malformed xml files are not included. Test validating the issue.
Please @reviewbybees @varmenise @batmat @oleg-nenashev
> [JENKINS-41653] Support core warning when collecting data

- Jenkinsfile
- pom.xml
- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/main/java/com/cloudbees/jenkins/support/impl/DumpExportTable.java
- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/UpdateCenter.java
According to [stats](http://stats.jenkins.io/pluginversions/support-core.html) there are almost no users on pre-2.60.x of 2.42 or newer versions, and that was released several weeks ago, so I think few people will be left behind.
@reviewbybees
> POM & baseline update

- src/main/java/com/cloudbees/jenkins/support/AsyncResultCache.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/api/CommandOutputContent.java
- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/main/java/com/cloudbees/jenkins/support/impl/EnvironmentVariables.java
- src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
- src/main/java/com/cloudbees/jenkins/support/impl/HeapUsageHistogram.java
- src/main/java/com/cloudbees/jenkins/support/impl/Metrics.java
- src/main/java/com/cloudbees/jenkins/support/impl/NetworkInterfaces.java
- src/main/java/com/cloudbees/jenkins/support/impl/RootCAs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SmartLogFetcher.java
- src/main/java/com/cloudbees/jenkins/support/impl/SystemConfiguration.java
- src/main/java/com/cloudbees/jenkins/support/impl/SystemProperties.java
- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
- src/main/java/com/cloudbees/jenkins/support/util/SystemPlatform.java
At least some of the incorrect usages seem to have been introduced in #53, and maybe people just copied it after that.
@reviewbybees
> Never needed to refer to RoleChecker

- src/main/java/com/cloudbees/jenkins/support/api/Component.java
Sezpoz actually does not seem to care, but let's use the right one to reduce the WTF/line ratio.
@reviewbybees
> Use the right ExtensionPoint class

- src/main/java/com/cloudbees/jenkins/support/util/Helper.java
please @reviewbybees UPDATE -> we found abnormal private usages of this API, but for temporary backward compat let's reintroduce it to give some more time to adapt, and then actually remove.
**UPDATE (@batmat): Helper removed in https://github.com/jenkinsci/support-core-plugin/pull/127**
> added to keep backward compatibility

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
Downstream to https://github.com/jenkinsci/jenkins/pull/3367
https://issues.jenkins-ci.org/browse/JENKINS-50428
@reviewbybees
> [JENKINS-50428] Take into account the now configurable location for (tasks) logging

- src/main/java/com/cloudbees/jenkins/support/configfiles/SecretHandler.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/SecretHandlerTest.java
See [JENKINS-50765](https://issues.jenkins-ci.org/browse/JENKINS-50765).
This does not seem to be an issue in practice, but hardening the code won't hurt.
@reviewbybees
> [JENKINS-50765] Defend SecretHandler from XXE attacks

- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
Rendered obsolete as of https://github.com/jenkinsci/jenkins/commit/a16c59bfb8b79738cde4f54783cfc432d027d7c3. I guess this plugin used to have a really old baseline.
> Deleting long-obsolete SlaveLogFetcher hack

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
I have no particularly opinion about the copyright statement (at least for the purpose of this PR), but simply put CloudBees open sourced this code, it is no longer `proprietary`, and leaving that statement live is inappropriate.
> This code is note proprietary anymore

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/main/java/com/cloudbees/jenkins/support/impl/ItemsContent.java
This PR intends to fix [JENKINS-33628](https://issues.jenkins-ci.org/browse/JENKINS-33628).
In an enterprise environment with thousands of jobs/builds, there is a big performance degradation produced by the computation of counting jobs/builds. When Jenkins is inside a Load Balancer, usually the HTTP session finished before the computation is done and this finish with the support-bundle being corrupted.
Support bundle is critical for Jenkins support organizations.
CC @escoem @aheritier
> [JENKINS-33628] Separate ItemsContent from AboutJenkins

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
Bumped the parent pom to latest and incrementalified the plugin so we have a release to easily test it on each build.
Cf. https://github.com/jenkinsci/incrementals-tools and [JEP-305](https://github.com/jenkinsci/jep/tree/master/jep/305)
> Incrementalify

- pom.xml
https://mvnrepository.com/artifact/org.assertj/assertj-core
> update assertj-core from 3.9.0 to 3.9.1 (latest 3.12.2)

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
https://issues.jenkins-ci.org/browse/JENKINS-58606
> JENKINS-58606 (OSS-2766) - Add info about backup plugins to support bundle

- src/main/java/com/cloudbees/jenkins/support/impl/SlaveCommandStatistics.java
- src/test/java/com/cloudbees/jenkins/support/impl/SlaveCommandStatisticsTest.java
https://issues.jenkins-ci.org/browse/JENKINS-58528
> Remove agent command statistics when agent is removed

- .github/release-drafter.yml
https://issues.jenkins-ci.org/browse/JENKINS-59211
> JENKINS-59211 (OSS-2772) - Add support for GH Release Drafter

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
https://issues.jenkins-ci.org/browse/JENKINS-59197
> JENKINS-59197 (OSS-2771) - Should report available processes for master

- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
- src/test/java/com/cloudbees/jenkins/support/impl/GCLogsTest.java
[JENKINS-58165](https://issues.jenkins-ci.org/browse/JENKINS-58165): Handle parameterized GC logs files name.
> [JENKINS-58165] Handle parameterized GC logs filenames

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/test/java/com/cloudbees/jenkins/support/SupportTestUtils.java
- src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
[JENKINS-56245](https://issues.jenkins-ci.org/browse/JENKINS-56245): Add the Jenkins Instance ID to the support bundle
> [JENKINS-56245] Add the Instance ID to AboutJenkins.

- pom.xml
https://issues.jenkins-ci.org/browse/JENKINS-59453
> JENKINS-59453 (OSS-2775) - Cleanup plugin dependencies / Move to BOM

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/api/BaseFileContent.java
- src/test/java/com/cloudbees/jenkins/support/actions/SupportAbstractItemActionTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/AbstractItemComponentTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/RunDirectoryComponentTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/RunningBuildsTest.java
This is to stay up-to-date and use the latest features and fixes.
> Upgrade parent pom & fix InputStream leak & fix tests

- src/test/java/com/cloudbees/jenkins/support/impl/RunningBuildsTest.java
Make sure that builds are really running when calling the support tooling.
So far only the tests for pipelines made sure with a semaphore that the build is still running. The tests for FreeStyle jobs worked by chance.
Scheduling a build now is also a bit simplified.
> Improve RunningBuildsTest

- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
Noticed a support bundle that had a ton of anonymous pool threads coming from this class.
> Use Computer.threadPoolForRemoting rather than creating a new Executors.newFixedThreadPool

- src/main/java/com/cloudbees/jenkins/support/impl/AgentProtocols.java
- src/test/java/com/cloudbees/jenkins/support/impl/AgentProtocolsTest.java
[JENKINS-36929](https://issues.jenkins-ci.org/browse/JENKINS-36929): Collect information about the agent protocols
> [JENKINS-36929] Collect Agents protocols information

- Jenkinsfile
- pom.xml
- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
This removes some dependencies from the hpi binaries, which shouldn't have been there in the first place
> Upgrade parent pom to 4.2

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
[JENKINS-59211](https://issues.jenkins-ci.org/browse/JENKINS-59211)
Enable Release Drafter through GitHub Actions.
> [JENKINS-59211] Enable release-drafter

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
[JENKINS-62746](https://issues.jenkins-ci.org/browse/JENKINS-62746) Adding Master Remoting version details to the bundle.
cc @aheritier
> [JENKINS-62746] Add remoting version details to about.md

- src/main/java/com/cloudbees/jenkins/support/impl/LoggerManager.java
The rest of the list doesn't have a .
> Remove the . for the all loggers entry

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
[JENKINS-64448](https://issues.jenkins.io/browse/JENKINS-64448)
> [JENKINS-64448] Move Remoting details below Java information

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
[JENKINS-64153](https://issues.jenkins.io/browse/JENKINS-64153)
> [JENKINS-64153] Always run cleanup upon generating bundle in background

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
[JENKINS-64263](https://issues.jenkins.io/projects/JENKINS/issues/JENKINS-64263)
> [JENKINS-64263] Log when an autogenerated bundle is deleted

- pom.xml
Please see https://issues.jenkins.io/browse/JENKINS-58979
And https://github.com/kohsuke/wordnet-random-name/pull/5
potential offensive word combination has been removed from wordnet.
> [JENKINS-58979] upgrade to wordnet 1.5 to avoid random offensive words.

- src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
- src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
[JENKINS-65854](https://issues.jenkins.io/browse/JENKINS-65854)
> [JENKINS-65854] Anonymize open File Descriptor paths

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/main/java/com/cloudbees/jenkins/support/impl/RootCAs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SmartLogFetcher.java
Some warnings discovered in this plugin when running Jenkins in "FIPS mode".
The findings where investigated and deemed compliant. So this is just noting down the result of the investigation
to be able to quickly reinvestigate future findings.
> Noting findings of FIPS warnings

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/java/com/cloudbees/jenkins/support/api/Component.java
- src/main/java/com/cloudbees/jenkins/support/filter/PrefilteredContent.java
Addressing the javadoc issues that fails the build at the moment:
```
[2021-07-06T03:34:47.110Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project support-core: MavenReportException: Error while generating Javadoc: 
[2021-07-06T03:34:47.110Z] [ERROR] Exit code: 1 - javadoc: error - Error fetching URL: https://javadoc.jenkins.io/
[2021-07-06T03:34:47.110Z] [ERROR] /home/jenkins/workspace/ugins_support-core-plugin_PR-299/src/main/java/com/cloudbees/jenkins/support/SupportAction.java:262: warning: no description for @throws
[2021-07-06T03:34:47.110Z] [ERROR]      * @throws ServletException
[2021-07-06T03:34:47.110Z] [ERROR]        ^
[2021-07-06T03:34:47.110Z] [ERROR] /home/jenkins/workspace/ugins_support-core-plugin_PR-299/src/ …
```
> Fix CI javadoc issues

- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
- src/test/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogsTest.java
[JENKINS-66003](https://issues.jenkins.io/browse/JENKINS-66003)
> [JENKINS-66003] Make Agent Launch Logs component available in Computer action

- pom.xml
Signed-off-by: Olivier Lamy <olamy@apache.org>
> Fix test which will fail when upgrading to remoting 4.8 (i.e core 2.294)

- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/UserCount.java
(all others are)
https://issues.jenkins.io/browse/JENKINS-67247
- ~[ ] Link to relevant pull requests, esp. upstream and downstream changes~
- ~[ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~ <<< Not sure what we could test
> [JENKINS-67247] Files paths should be relatives

- .github/CODEOWNERS
Adding @jenkinsci/support-core-plugin-developers as codeowners to automatically request for review.
> Add CODEOWNERS for automatic review request

- README.md
[SECURITY-2186](https://issues.jenkins.io/browse/SECURITY-2186) was already pushed to master but without properly written description, I think it would be useful to update readme
> [SECURITY-2186] follow-up documentation

- .github/dependabot.yml
- .github/release-drafter.yml
- .github/workflows/cd.yaml
- .mvn/maven.config
- pom.xml
As per https://www.jenkins.io/doc/developer/publishing/releasing-cd/
Note: CD already enabled at https://github.com/jenkins-infra/repository-permissions-updater/pull/2144.
cc @jenkinsci/company-cloudbees-developers
> [chore] Automated CD Release

- CHANGELOG.md
Rather than "master" use "controller"
~Ensure you have provided tests - that demonstrate the feature works or fixes the issue~
> Make a comment more inclusive

- pom.xml
fixed update plugin pom and bom as well reincrementalified so I can test with incremental
> bump jenkins version and bom

- src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
This is pretty self explanatory.
> `ContentMappings` should implement `getCategory` now that baseline is past 2.226

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/SupportLogHandler.java
- src/main/java/com/cloudbees/jenkins/support/api/BaseFileContent.java
- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
- src/main/java/com/cloudbees/jenkins/support/impl/ItemsContent.java
- src/main/java/com/cloudbees/jenkins/support/threaddump/HighLoadCpuChecker.java
> Upgrade SpotBugs to latest

- Jenkinsfile
- pom.xml
- src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
Clones and rebases https://github.com/jenkinsci/support-core-plugin/pull/413
> Update build toolchain

- pom.xml
To help https://github.com/jenkinsci/support-core-plugin/pull/441 move forward
> [chore] Add exclusion for byte-buddy in assertj-core

- README.md
Per discussion with @omehegan this can be removed
> [chore] Cleanup third party support section

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
[JENKINS-71226](https://issues.jenkins.io/browse/JENKINS-71226)
Add FINE logging of what components are being processed and what content are being written. This can help identify slow components/content quickly. And is a cheap addition while we come up with a more elaborate Stats solution https://issues.jenkins.io/browse/JENKINS-61815.
> [JENKINS-71226] Add logging to help identify faulty components

- src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
- src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
If you are unsure how something works, sometimes the answer is that it does not. https://github.com/jenkinsci/support-core-plugin/pull/473#discussion_r1230861903
> [JENKINS-71464] Fix `GetUlimit` anonymization

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/api/BaseFileContent.java
- src/main/java/com/cloudbees/jenkins/support/filter/AllContentFilters.java
- src/main/java/com/cloudbees/jenkins/support/filter/ContentFilter.java
- src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
- src/main/java/com/cloudbees/jenkins/support/filter/InetAddressContentFilter.java
- src/main/java/com/cloudbees/jenkins/support/filter/SensitiveContentFilter.java
- src/main/java/com/cloudbees/jenkins/support/filter/WordTrie.java
- src/main/java/com/cloudbees/jenkins/support/filter/WordsTrie.java
- src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
- src/main/java/com/cloudbees/jenkins/support/slowrequest/SlowRequestChecker.java
- src/main/java/com/cloudbees/jenkins/support/util/WordReplacer.java
- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/AgentsConfigFileTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/RunningBuildsTest.java
- src/test/java/com/cloudbees/jenkins/support/util/WordReplacerTest.java
[JENKINS-57138](https://issues.jenkins.io/browse/JENKINS-57138) Improved the Anonymization resource usage and process times. The anonymization of Sensitive Content (Jenkins item, users, labels, etc) is extremely slow:
* It regenerates search and replacement lists for every single line
* the ignore case scenario requires to change the casing of both the input and content mapping word, redundantly
After addressing some of those issues, the timings were improved a bit. But I then try to use a general `Pattern` compiled with all content mappings and apply it for every line which considerably improved the efficiency!
Then reading through Regex optimization techniques, I extracted the first characters of content mapping words to reduce backtracking. For example instead of `a|abc|abcd|bcd)` use …
> [JENKINS-57138] Address anonymization performance issues

- src/main/java/com/cloudbees/jenkins/support/util/CallAsyncWrapper.java
Arguably more legible code, noticed while working on #486.
> Simplification of `CallAsyncWrapper`

- src/main/java/com/cloudbees/jenkins/support/api/Content.java
- src/test/java/com/cloudbees/jenkins/support/util/Chrono.java
> Fix javac warning in `new Content(String)`

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/filter/ContentFilter.java
Trying to leverage the existing Anonymization stack of Support Core from an external plugin, I noticed some problems. `ContentFilter`s may generate mappings when filtering or when reloading, so when generating the content with anonymization, one need access to the singleton to avoid performance problems:
* https://github.com/jenkinsci/support-core-plugin/blob/c7f0a46f9e6cf50656fc46d209e9aa886fc3880c/src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java#L380
* https://github.com/jenkinsci/support-core-plugin/blob/c7f0a46f9e6cf50656fc46d209e9aa886fc3880c/src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java#L555-L556
Therefore:
* I am proposing to relax access to the Singleton, while still restricting most methods.
Note: I also think that we would eventually externalize …
> Replace class restriction to method levels of ContentMappings

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/api/Container.java
A special component defined in CloudBees CI in high availability mode gathers information from other controller replicas. To make this properly reflect the admin’s selection it is necessary to expose that selection to other components. This information was not previously available, though it is easy to pass.
> Define `Container.getComponents`

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
https://github.com/jenkinsci/jenkins/pull/9311
> Remove usages of Commons Compress

- src/main/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitors.java
- src/test/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitorsTest.java
[JENKINS-73712](https://issues.jenkins.io/browse/JENKINS-73712)
> [JENKINS-73712] Anonymize OldDataMonitor details in admin-monitors.md

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
See https://github.com/jenkinsci/stapler/pull/596. Minor merge conflict with #584.
> Work around NPE in `Stapler.getCurrent`

- src/main/java/com/cloudbees/jenkins/support/filter/DefaultStopWords.java
Add more words that should not be anonymised:
* tmp
* git
* retry
* vault
* exists
> [chore] Add more anonymisation stop words

- src/main/java/com/cloudbees/jenkins/support/filter/DefaultStopWords.java
Those two came up in a security fix discussion (but they are not security related) a while ago, I never came around to integrate them until now...
> [chore] Add more stop words

- src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
- src/test/java/com/cloudbees/jenkins/support/impl/CustomLogsTest.java
https://github.com/jenkinsci/support-core-plugin/pull/627#issuecomment-2672175832 Windows test failure not noticed in #624.
> Close all files in `CustomLogsTest`

- src/main/java/com/cloudbees/jenkins/support/impl/ItemsContent.java
The `legacyIds` marker file will stop getting created after https://github.com/jenkinsci/jenkins/pull/10456, `buildCount` will stop working after that. (As part of jira [JENKINS-75465](https://issues.jenkins.io/browse/JENKINS-75465))
The datetime based counting is no longer necessary as that is applicable only if Jenkins controller is running `1.596` (2015/01/04) or below version.
This PR proposes to always count builds by build numbers.
The logic for `legacyIds` was introduced in 2019, [ref commit](https://github.com/jenkinsci/support-core-plugin/commit/41a8fb54ba5652ea26f9bdf89c303a31ab4b71d6#diff-66ef5e9b98bf40c9b1e73ab8ed4c3fbb51757b49e3f4b7c072808e8287c00c6aR96-R116).
There are no other cleanup needed (not tests found around `legacyIds` file existence)
* Manual code analysis and …
> [JENKINS-75465] Do not support datetime based build directories as it is 10 yrs since migration

- src/main/resources/com/cloudbees/jenkins/support/SupportAction/progressPage.jelly
> Migrate to EE 9 in Jelly view

- src/main/java/com/cloudbees/jenkins/support/impl/ProxyConfiguration.java
- src/test/java/com/cloudbees/jenkins/support/impl/ProxyConfigurationTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/UpdateCenterTest.java
[JENKINS-73599](https://issues.jenkins.io/browse/JENKINS-73599). Proxy Configuration and Update Center are now separated in Jenkins core so it makes sense to separate the information in the bundle as well.
> [JENKINS-73599] Externalize Proxy details in its own component + fix markdowns

- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
- src/main/java/com/cloudbees/jenkins/support/slowrequest/SlowRequestThreadDumpsGenerator.java
- src/main/java/com/cloudbees/jenkins/support/startup/ShutdownComponent.java
- src/main/java/com/cloudbees/jenkins/support/startup/StartupComponent.java
- src/main/java/com/cloudbees/jenkins/support/startup/StartupReport.java
- src/test/java/com/cloudbees/jenkins/support/startup/ShutdownComponentTest.java
- src/test/java/com/cloudbees/jenkins/support/startup/StartupReportTest.java
Collect timings for each init milestone
If the startup takes more than a defined initial delay, start collecting thread dumps at regular intervals, until the startup completes.
We consider that an instance taking more than 5 minutes is slow to start and is worth collecting thread dumps for (`com.cloudbees.jenkins.support.startup.StartupReport.INITIAL_DELAY_SECONDS`).
Then we take one thread dump every 30 seconds (`com.cloudbees.jenkins.support.startup.StartupReport.RECURRENCE_PERIOD_SECONDS`)
The timings are collected in `startup-timings.md` with the following format (values for a development instance)
---
| Milestone                          | Time     |
|------------------------------------|----------|
| Started initialization             | No data  |
| Listed all plugins …
> Collect information about instance startup and shutdown

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/BundleFileName.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/SecretHandler.java
- src/main/java/com/cloudbees/jenkins/support/filter/ContentFilter.java
- src/main/java/com/cloudbees/jenkins/support/filter/PasswordRedactorRegexBuilder.java
- src/main/java/com/cloudbees/jenkins/support/filter/SensitiveContentFilter.java
- src/main/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitors.java
- src/main/java/com/cloudbees/jenkins/support/impl/DirectoryComponent.java
- src/main/java/com/cloudbees/jenkins/support/impl/LoadStats.java
- src/main/java/com/cloudbees/jenkins/support/impl/NodeExecutors.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SmartLogFetcher.java
- src/main/resources/com/cloudbees/jenkins/support/impl/DirectoryComponent/help-defaultExcludes.groovy
Migrate from deprecated/EOL Commons Lang 2 to Commons Lang 3.
> Upgrade Commons Lang from 2 to 3
