- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
The URL to the plugins was not correct. The plugins are behind `$JENKINS_UC/download/plugins` where "download" was missing.
When there are some plugins, the limit of docker image layer is exceeded. Using a single `RUN curl` command with multiple `-L url -o file` options to download all the plugins.
> Some Dockerfile generation fix: number of layer, url to plugins

- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
A JVM thread dump surrounds the thread names with double-quotes
and IntelliJ requires this to parse a thread dump.
> Quote thread name in thread dumps

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/resources/com/cloudbees/jenkins/support/SupportAction/index.jelly
`l:layout` only accepts string values for the title parameter.
> [JENKINS-23278] Fix html title tag to properly display action title.

- src/main/java/com/cloudbees/jenkins/support/impl/SmartLogFetcher.java
Observed in a bundle (ref. ZD-24585):
```
…	WARNING	c.c.j.support.impl.JenkinsLogs#addContents: Could not retrieve some of the remote node extra logs
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at …
Caused by: java.lang.NullPointerException
at com.cloudbees.jenkins.support.impl.SmartLogFetcher$LogFileHashSlurper.invoke(SmartLogFetcher.java:251)
at com.cloudbees.jenkins.support.impl.SmartLogFetcher$LogFileHashSlurper.invoke(SmartLogFetcher.java:236)
at …
at ......remote call to …(Native Method)
at …
at com.cloudbees.jenkins.support.impl.SmartLogFetcher$ForNode.getLogFiles(SmartLogFetcher.java:100)
at com.cloudbees.jenkins.support.impl.JenkinsLogs$4.call(JenkinsLogs.java:327)
at …
```
> File.listFiles can return null

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
Otherwise I have seen
```
FROM jenkins:1.580.2
RUN mkdir -p /usr/share/jenkins/ref/plugins/
…
RUN curl -L $JENKINS_UC/plugins/nectar-license/6.0/nectar-license.hpi -o /usr/share/jenkins/ref/plugins/nectar-license.jpi
RUN curl -L $JENKINS_UC/plugins/nectar-rbac/4.12/nectar-rbac.hpi -o /usr/share/jenkins/ref/plugins/nectar-rbac.jpi
RUN curl -L $JENKINS_UC/plugins/nectar-vmware/4.3.2/nectar-vmware.hpi -o /usr/share/jenkins/ref/plugins/nectar-vmware.jpi
…
```
which will not work.
@reviewbybees but esp. @alecharp who seems to have worked on this recently. (A new release would be in order soon, no?)
> Use the CB UC whenever nectar-license is installed

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
Limit the winsw log files to `MAX_FILE_SIZE`. The `jenkins.err.log` file can be several MB, so we should limit the size.
@reviewbybees
> Add file size limit to winsw logs

- src/main/java/com/cloudbees/jenkins/support/api/CommandOutputContent.java
- src/main/java/com/cloudbees/jenkins/support/impl/JVMProcessSystemMetricsContents.java
- src/main/java/com/cloudbees/jenkins/support/impl/SystemConfiguration.java
- src/main/java/com/cloudbees/jenkins/support/util/SystemPlatform.java
> Add some Unix system metrics and configuration contents

- src/main/java/com/cloudbees/jenkins/support/slowrequest/InflightRequest.java
- src/test/java/com/cloudbees/jenkins/support/slowrequest/InflightRequestTest.java
This pull request adds the username of the person experiencing slow http requests. It also adds the referrer header in the event a plugin invokes the api and is unaware of it.
@reviewbybees
> [JENKINS-24671] Add username and referrer to slow-requests

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
Fix a NPE when running unit tests at the start of the test:
```
Caused by: java.lang.NullPointerException
at com.cloudbees.jenkins.support.SupportPlugin.loadConfig(SupportPlugin.java:384)
``` 
@reviewbybees
> Prevent NPE in unit test

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
I think that if we didn't create ServletOutputStream then we don't need to close it. I think it should me managed by the container and we shouldn't force a close. This was creating `ClientAbortException`.
> [FIXED JENKINS-26409] ClientAbortException logged when cancelling a support bundle download

- src/main/java/com/cloudbees/jenkins/support/impl/NetworkInterfaces.java
- src/test/java/com/cloudbees/jenkins/support/impl/NetworkInterfacesTest.java
Add an option to obtain information about the networking interfaces that are part of the computer.
@reviewbybees
> Add networking interface information to support bundle

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
https://issues.jenkins-ci.org/browse/JENKINS-29034
> [JENKINS-29034] - Modify filename to include date and time

- src/test/java/com/cloudbees/jenkins/support/impl/BuildQueueTest.java
Currently this unit test has a race condition when performing a release and is currently preventing a new release. Unit tests work when running with `mvn test`, and `mvn install`, however fail consistently when a release is performed.
@reviewbybees
> Ignore build queue unit test

- src/main/java/com/cloudbees/jenkins/support/api/TruncatedContent.java
- src/main/java/com/cloudbees/jenkins/support/api/TruncationException.java
- src/main/java/com/cloudbees/jenkins/support/impl/DumpExportTable.java
- src/test/java/com/cloudbees/jenkins/support/SupportTestUtils.java
- src/test/java/com/cloudbees/jenkins/support/impl/DumpExportTableTest.java
Could be useful for detecting certain types of memory leaks.
> Add option to dump export tables for slave nodes.

- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
- src/main/java/com/cloudbees/jenkins/support/timer/DeadlockTrackChecker.java
- src/test/java/com/cloudbees/jenkins/support/timer/DeadlockTest.java
Too often the actual cause of the deadlock is outside the first ThreadInfo.MAX_FRAMES (i.e. 8) thread frames.
When that happens the actual deadlock information is worse than useless.
This change uses the same formatter as the full thread dump which should result in more useful information
@reviewbybees
> Capture the full stacktrace for any deadlocked threads

- src/main/java/com/cloudbees/jenkins/support/SupportLogFormatter.java
The format method should be thread safe as it could be invoked from
multiple threads. Instead of using a MessageFormatter which is not thread safe we
use the FastDateFormatter, and a StringBuffer both of which are thread
safe.
@reviewbybees
> [JENKINS-30117] Support bundle blocks with lots of data

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
Previous implementation used a `Channel.call` which performs a synchronous callable. Instead we can use the `Channel.callAsync` in order to prevent the channel from blocking.
@reviewbybees
> [JENKINS-28216] Obtain slave logs using async callable.

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
Sometimes it is necessary to increase the max log rotation size to maintain the history of logs for a few days. This allows you to keep a max rotation size to keep.
@reviewbybees
> Add argument to increase max rotate log size.

- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
- src/test/java/com/cloudbees/jenkins/support/timer/DeadlockTest.java
Saw a support bundle from someone presumably using this plugin <2.28 and was annoyed by a deadlock file which hinted at [JENKINS-31614](https://issues.jenkins-ci.org/browse/JENKINS-31614) yet lacked the crucial detail of the caller of `Queue.schedule`.
#41 seems to have fixed this, but included no test addition to prove it. Doing so now.
I originally fixed this against an older version of the plugin using the methods already available in `Functions` in Jenkins core. For some reason these do not seem to be showing full lock information in this context, though. Original display:
```
==============
Deadlock Found
==============
"Thread-12" Id=45 BLOCKED on java.lang.Object@7c60aaa5 owned by "Thread-11" Id=44
at com.cloudbees.jenkins.support.timer.DeadlockTest$2.run(DeadlockTest.java:78)
- …
```
> Verifying full stack traces in deadlocks

- src/main/java/com/cloudbees/jenkins/support/impl/LoggerManager.java
Sometimes a logger could be causing performance issues because it is far too verbose. This will display which loggers are currently enabled, and what the log level is for each logger. 
@reviewbybees @daniel-beck
> [FIX JENKINS-32401] Record log levels

- src/main/java/com/cloudbees/jenkins/support/SupportLogFormatter.java
Attempt to avoid a deadlock observed in remoting by not causing any remote
classes to be loaded when we are logging.
@reviewbybees 
[JENKINS-32622](https://issues.jenkins-ci.org/browse/JENKINS-32622)
> [JENKINS-32622] Switch to a ThreadLocal DateFormatter

- src/main/java/com/cloudbees/jenkins/support/impl/LoggerManager.java
Null pointer exception is now reported in my jenkins.log.  This should prevent it.
> Prevent null pointer exception reporting log level

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
This should help improve the performance of generating a support bundle and the size if you do not require logs from each individual slave. Some Jenkins masters have a few hundred slaves, so generating a support bundle might take a long time. Also some of the machines might have logs which might be several MB in size.
This pull request disables obtaining slave logs by default. Unless the user(s) have had issues with the slave machines, the log information for each individual slave is most likely is not required.
@reviewbybees
> Separate slave logs, and master logs.

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
In certain situations Jenkins will take a very long time to start up. We add some new diagnostic information when the Jenkins plugin is loaded to obtain more information about what threads are currently running which could be causing the slow startup. The diagnostic information is only gathered until the `InitMilestone.COMPLETED` is reached in which case the thread dump stops being generated. By default this is disabled and the default time interval is 60 seconds, but can be customized via java arguments.
@reviewbybees
> Diagnose the startup performance

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
https://issues.jenkins-ci.org/browse/JENKINS-37772
@reviewbybees
> [JENKINS-37772] - Get rid of Initializer(after =  InitMilestone.COMPLETED)

- src/main/java/com/cloudbees/jenkins/support/SupportLogFormatter.java
- src/test/java/com/cloudbees/jenkins/support/SupportLogFormatterTest.java
See https://github.com/jenkinsci/workflow-job-plugin/pull/31 for an example.
- missing newline between header and start of exception
- gratuitous newline after stack trace
- spurious `: null` when a logger reported an exception without a message
@reviewbybees
> Fixed some buglets in SupportLogFormatter

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
- src/test/java/com/cloudbees/jenkins/support/impl/GCLogsTest.java
>When diagnosing an issue, having GC logs when enabled can be critical. It would be both simpler for everyone and useful to have them added to the bundle automatically too.
The code here introspects the VM and parses `-Xloggc` and so on to find and gather those logs.
https://issues.jenkins-ci.org/browse/JENKINS-39607
@jenkinsci/code-reviewers 
Possibly for more eyes: @reviewbybees esp. @svanoort
> [FIX JENKINS-39607] GC logs should be collected

- LICENSE.md
All files in the support core plugin should be licensed under MIT (unless specified otherwise).
@reviewbybees esp @stephenc and @jglick
> Add license file.

- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
Observed by just installing this plugin and restarting Jenkins.
```
… com.cloudbees.jenkins.support.SupportPlugin writeBundle
WARNING: Could not get content from 'Garbage Collection Logs' for support bundle
java.lang.NullPointerException
at java.io.File.<init>(File.java:277)
at com.cloudbees.jenkins.support.impl.GCLogs.addContents(GCLogs.java:84)
at com.cloudbees.jenkins.support.SupportPlugin.writeBundle(SupportPlugin.java:311)
at com.cloudbees.jenkins.support.SupportPlugin.writeBundle(SupportPlugin.java:274)
at com.cloudbees.jenkins.support.SupportPlugin$PeriodicWorkImpl$1.run(SupportPlugin.java:724)
at java.lang.Thread.run(Thread.java:745)
```
`Component.isEnabled` is ignored by `SupportPlugin.writeBundle(OutputStream)`. Possibly `GCLogs` should not even bother overriding it—just treat …
> NPE in GCLogs.addContents

- src/main/java/com/cloudbees/jenkins/support/impl/RemotingDiagnostics.java
Since this plugin cannot assume the version of core, access the method
in question via reflection (and also report the failure to find that
method, so that we have evidence either way.)
@reviewbybees
> [FIXED JENKINS-39150] report remoting diagnostics when it's available

- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
@reviewbybees esp. @jglick as you rightly advised for that change in https://github.com/jenkinsci/support-core-plugin/pull/89#issuecomment-264277965
State currently:
> Simply ignore if the GC logging options are not enabled

- src/main/java/com/cloudbees/jenkins/support/BundleNameInstanceTypeProvider.java
- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/java/com/cloudbees/jenkins/support/SupportCommand.java
- src/main/java/com/cloudbees/jenkins/support/SupportLogFormatter.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/test/java/com/cloudbees/jenkins/support/BundleNamePrefixTest.java
[JENKINS-40098](https://issues.jenkins-ci.org/browse/JENKINS-40098)
Refactored the existing code to use the same logic for choosing the bundle filename, and introduced a change enabling both overriding through using a sysprop, or implementing a new Extension Point.
The approach with Extension Points should enable more dynamic needs, when the sysprop one will be immediately usable by anyone without having to develop an extension.
Note: if found, the extension is preferred over the sysprop.
@reviewbybees esp. @jglick who pointed me to SupportProvider.getName() I had missed in the first attempt. 
Supersedes #91
> [JENKINS-40098] Bundle naming strategy should be able to specify an instance type

- src/main/java/com/cloudbees/jenkins/support/api/TemporaryFileContent.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/AgentsConfigFile.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/ConfigFileComponent.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponent.java
- src/main/resources/com/cloudbees/jenkins/support/configfiles/Messages.properties
- src/test/java/com/cloudbees/jenkins/support/configfiles/AgentsConfigFileTest.java
[JENKINS-40062](https://issues.jenkins-ci.org/browse/JENKINS-40062)
Downstream of #95 ([JENKINS-40094](https://issues.jenkins-ci.org/browse/JENKINS-40094)) - [These are the real changes](https://github.com/amuniz/support-core-plugin/compare/JENKINS-40094...amuniz:JENKINS-40062).
This add agents `config.xml` to the bundle (optionally) - deselected by default
@reviewbybees @cloudbees/team-cjp
> [JENKINS-40062] Optionally add agents config.xml

- src/main/java/com/cloudbees/jenkins/support/SupportLogFormatter.java
- src/main/java/com/cloudbees/jenkins/support/SupportLogHandler.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/main/java/com/cloudbees/jenkins/support/impl/LoadStats.java
- src/main/java/com/cloudbees/jenkins/support/slowrequest/SlowRequestChecker.java
- src/main/java/com/cloudbees/jenkins/support/timer/DeadlockTrackChecker.java
- src/test/java/com/cloudbees/jenkins/support/SupportLogFormatterTest.java
When trying to evaluate a complex support bundle, or series of bundles, perhaps attempting to align different log files to determine the root cause of a single event, possibly crossing machines…it is very tricky to keep track of multiple local timezones plus UTC. This patch just forces the support bundle to use UTC consistently: most importantly, in log timestamps, and in the name of the bundle ZIP itself.
@reviewbybees
> Use UTC for all timestamps

- src/main/java/com/cloudbees/jenkins/support/api/FileContent.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/AgentsConfigFile.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/ConfigFileComponent.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponent.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/SecretHandler.java
- src/main/java/com/cloudbees/jenkins/support/configfiles/XmlRedactedSecretFileContent.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponentTest.java
[JENKINS-42393](https://issues.jenkins-ci.org/browse/JENKINS-42393)
Realigning File.createTempFile call to others already existing in the support-core plugin codebase. And avoid unnecessary network sync for temporary files in the go.
@reviewbybees esp. @varmenise @cyrille-leclerc @christ66
> [JENKINS-42393] Temporary files should not be created in the bundles root directory under JENKINS_HOME

- src/main/java/com/cloudbees/jenkins/support/api/TemporaryFileContent.java
If the `writeTo` method fails we still should perform the delete no matter what happens.
@reviewbybees esp. @varmenise
> Delete even if write to bundle fails.

- src/main/java/com/cloudbees/jenkins/support/SupportCommand.java
Tested against https://github.com/jenkinsci/jenkins/pull/2795 in `-remoting`, `-ssh`, and `-http` modes.
@reviewbybees
> [JENKINS-41745] Allow SupportCommand to work without a Remoting channel

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
Otherwise, in plugins which depend on this one (like `workflow-cps`), every now and then the bundle generator will start to run while the test is running. Sometimes that is harmless (if a waste of time); sometimes it starts to run while Jenkins is shutting down, resulting in various stupid exceptions and the like being printed to the console. Harmless but confusing.
@reviewbybees
> Suppress PeriodicWorkImpl during functional tests

- src/main/java/com/cloudbees/jenkins/support/impl/SystemConfiguration.java
[JENKINS-40077](https://issues.jenkins-ci.org/browse/JENKINS-40077)
@reviewbybees
> [FIX JENKINS-33203] trick to execute 'dmesg --ctime' if it is available if not 'dmesg'

- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
- src/test/java/com/cloudbees/jenkins/support/SupportLogFormatterTest.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponentTest.java
The contents of actual and expected value are still equal except for the windows line endings in the actual value which results in assertion error. 
Need an advice on how to better fix this. At the moment, I just used a Hamcrest matcher that ignores the whitespaces.
This seems to have identified Windows compatibility defect in the GCLogs collector. The full path of the file was used to form a RegEx pattern. Due to path separator difference, the logic fails on Windows but works fine on Linux, i.e. `\` is an escape character in RegEx so windows path causes a compilation error.
@reviewbybees
> Attempt at Fixing the Windows Test Run

- src/main/java/com/cloudbees/jenkins/support/impl/HeapHisto.java
- src/main/java/com/cloudbees/jenkins/support/impl/HeapUsageHistogram.java
Added heap histogram generation component using _com.sun.management:type=DiagnosticCommand_ object and _GC.class_histogram_ command.
Only for master instance currently, the new component generates nodes/master/heap-histogram.txt file. Can be disabled with the option _Master Heap Histogram -histo:live_ 
please @reviewbybees
> [JENKINS-22791] Record heap histograms

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
https://issues.jenkins-ci.org/browse/JENKINS-47779
Since Jenkins 2.86, pluginManager is returning an unmodifiable list each time getPlugins is called. 
Support core plugin was sorting the list by using Collections.sort thus currently is throwing UnsupportedOperationException.
Please, @reviewbybees @christ66 @andresrc @oleg-nenashev
> [FIXED JENKINS-47779] Could not attach 'plugins/active.txt' to support bundle

- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
Seems that diagnostics in #100 cause an error as of https://github.com/jenkinsci/jenkins/pull/2792; observed in a support bundle a `manifest/errors.txt`:
```
Could not attach 'nodes/master/thread-dump.txt' to support bundle
-----------------------------------------------------------------------
java.lang.ClassCastException: jenkins.security.ImpersonatingScheduledExecutorService cannot be cast to java.util.concurrent.ScheduledThreadPoolExecutor
at com.cloudbees.jenkins.support.impl.ThreadDumps$1.writeTo(ThreadDumps.java:90)
at com.cloudbees.jenkins.support.SupportPlugin.writeBundle(SupportPlugin.java:359)
at com.cloudbees.jenkins.support.SupportPlugin.writeBundle(SupportPlugin.java:273)
at com.cloudbees.jenkins.support.SupportPlugin$PeriodicWorkImpl$1.run(SupportPlugin.java:761)
at …
```
> Fixing a ClassCastException

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
This restores backward compatibility on the endpoint `/support/download`, as well as adding tests checking that the endpoints remain valid.
@reviewbybees
> [JENKINS-48436] Restore backward compatibility on web endpoints

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
Just code cleanup.
@reviewbybees
> threadDumpLegacy seems to be obsolete as of some long-past Java baseline update

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
Picks up https://github.com/jenkinsci/jenkins/pull/2490. I saw a bundle whose `nodes/master/file-descriptors.txt` included a lot of entries like
/var/lib/jenkins/support/cache/…/all_2017-…04.log
and maybe this is why.
@reviewbybees
> Switch to RewindableFileOutputStream

- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
Otherwise it is cumbersome to find threads of a particular kind, like all `Executor`s. The ID is still recorded in the file; this just changes the display order to something I think will be more helpful for humans.
@reviewbybees
> Sort thread dumps by name rather than ID

- src/main/java/com/cloudbees/jenkins/support/impl/HeapUsageHistogram.java
https://issues.jenkins-ci.org/browse/JENKINS-49931
@svanoort @reviewbybees please review.
Now the histogram is disabled by default, thus you will need to enable it either adding a system property _-Dcom.cloudbees.jenkins.support.impl.HeapUsageHistogram.DISABLED=false_ or running  from Script Console the line _com.cloudbees.jenkins.support.impl.HeapUsageHistogram.DISABLED=false_
Yes, the system property and the direct assignment have the same path/name.
> [FIXED JENKINS-49931] Heap Histogram Collection Destabilizes Masters

- src/main/java/com/cloudbees/jenkins/support/impl/RootCAs.java
- src/test/java/com/cloudbees/jenkins/support/impl/RootCAsTest.java
Links below provide some explanation example as to how to get the actual
trust store for inspection. They were used to replace the current broken
code which simply tries to enumerate empty KeyStore.
https://github.com/jenkinsci/jenkins-scripts/pull/82/files
https://stackoverflow.com/questions/8884831/listing-certificates-in-jvm-trust-store
> JENKINS-49668 - Root CAs component is fixed.

- src/main/resources/com/cloudbees/jenkins/support/SupportAction/index.jelly
The deletion is definitive and having a visual warning can help prevent human errors.
Here's the result:
@jtnord @reviewbybees
> [JENKINS-49578] Improve deletion button warning

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/filter/DataFaker.java
- src/main/java/com/cloudbees/jenkins/support/filter/InetAddressContentFilter.java
- src/main/java/com/cloudbees/jenkins/support/filter/NameProvider.java
- src/main/java/com/cloudbees/jenkins/support/filter/SensitiveContentFilter.java
- src/test/java/com/cloudbees/jenkins/support/filter/FilteredOutputStreamTest.java
- src/test/java/com/cloudbees/jenkins/support/util/OutputStreamSelectorTest.java
Using snakeyaml without shading it is a little precarious in the current Jenkins ecosystem, see the comments in [JENKINS-50202](https://issues.jenkins-ci.org/browse/JENKINS-50202) for details.
This PR replaces the javafaker library with [wordnet-random-name](https://github.com/kohsuke/wordnet-random-name). It doesn't allow us to use different themes for different kinds of data (which might be a blocker), but it has no compile-scope dependencies.
We could also downgrade to snakeyaml 1.17 to avoid API compatibility issues for now (assuming javafaker 0.15 is compatible with snakeyaml 1.17), or we could shade it and the javafaker library to avoid conflicts with other plugins, but getting rid of it seemed like the easiest long-term solution.
@reviewbybees
> [JENKINS-52639] Remove snakeyaml dependency by switching to wordnet-random-name

- pom.xml
This helps fix some annoying development issues amongst plenty of other
goodies since the previously used version (3.2).
@reviewbybees @dwnusbaum
> Upgrade plugin parent to 3.19

- src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
- src/test/java/com/cloudbees/jenkins/support/filter/ContentMappingsTest.java
- src/test/java/com/cloudbees/jenkins/support/filter/SensitiveContentFilterTest.java
- src/test/resources/com/cloudbees/jenkins/support/filter/ContentMappingsTest/operatingSystemIncludedAsStopWord/com.cloudbees.jenkins.support.filter.ContentFilters.xml
- src/test/resources/com/cloudbees/jenkins/support/filter/ContentMappingsTest/operatingSystemIncludedAsStopWord/com.cloudbees.jenkins.support.filter.ContentMappings.xml
See [JENKINS-54688](https://issues.jenkins-ci.org/browse/JENKINS-54688)
Due to [JENKINS-21670](https://issues.jenkins-ci.org/browse/JENKINS-21670) the Operating System information from the master node in _about.md_ or any nodes in _nodes.md_ could be anonymised if they are used as label (a classical practice), causing confusion and making difficult to get deeper information in the support bundle. This PR tries to be a quick win so adding the common operating systems' names as stop words avoid the anonymisation.
@reviewbybees spec. @varyvol @jvz @aheritier
> [JENKINS-54688] Operating System informations are anonymized

- src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
- src/test/java/com/cloudbees/jenkins/support/filter/ContentMappingsTest.java
- src/test/java/com/cloudbees/jenkins/support/filter/InetAddressContentFilterTest.java
Without these changes, the first class function poisons the environment for the second class function.
Similar problems exist in the underlying class...
> Fix running InetAddressContentFilterTest as a set

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/main/java/com/cloudbees/jenkins/support/util/Markdown.java
- src/test/java/com/cloudbees/jenkins/support/util/MarkdownTest.java
The goal here is to be able to fix the markdown generation by this plugin.
https://issues.jenkins-ci.org/browse/JENKINS-54922
Currently, it generates:
```
* computer_reliable_bulletin (`user_junior_process.slaves.DumbSlave`)
- Description:    _Java 8_
- Executors:      1
- Remote FS root: `/home/jenkins`
- Labels:         label_transparent_court label_religious_blood pipeline view_medieval_corn label_mutual_violation label_related_favourite label_easy_insurance
```
Which, in **MacDown.app** renders as :
* computer _reliable_ bulletin (`user_junior_process.slaves.DumbSlave`)
- Description:    _Java 8_
- Executors:      1
- Remote FS root: `/home/jenkins`
- Labels:         label _transparent_ court label _religious_ blood pipeline view _medieval_ corn label _mutual_ violation label …
> [JENKINS-54922] Markdown

- pom.xml
- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
[JENKINS-55493](https://issues.jenkins-ci.org/browse/JENKINS-55493)
This is required to validate the plugin with PCT against Java 11 support. It will require to upgrade `metrics` plugin version requirement to include the fix from https://github.com/jenkinsci/metrics-plugin/pull/42 once released but that can be done in a follow-up PR.
@jenkinsci/java11-support
> [JENKINS-55493] Upgrade parent pom and solve JTH html API usage 

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
[JENKINS-55014](https://issues.jenkins-ci.org/browse/JENKINS-55014)
In order to try to prevent a deadlock when the support bundle is generated at startup, try to preload `PrintWriter` and `Throwable` classes.
Idea from @dwnusbaum.
cc @oleg-nenashev
> [JENKINS-55014] Preload PrintWriter and Throwable

- src/main/java/com/cloudbees/jenkins/support/util/WordReplacer.java
- src/test/java/com/cloudbees/jenkins/support/filter/SensitiveContentFilterTest.java
- src/test/java/com/cloudbees/jenkins/support/util/WordReplacerTest.java
See [JENKINS-55866](https://issues.jenkins-ci.org/browse/JENKINS-55866)
Previous PR was: https://github.com/jenkinsci/support-core-plugin/pull/163
This is a follow up ticket to fix the replacements with empty strings, a test and avoid flaky test that happened to me during testing.
@reviewbybees Specially: @varyvol @fcojfernandez @jvz
> [JENKINS-55866] Fix replacement with empty strings

- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SmartLogCleaner.java
- src/test/java/com/cloudbees/jenkins/support/impl/SmartLogCleanerTest.java
https://issues.jenkins-ci.org/browse/JENKINS-50297
The issue was not only impacting over `winsw` agents logs but in every agent log. 
`SmartLogFetcher` is not removing the cache entries created by agents that are no longer attached to Jenkins. Sometimes these directories can take a big amount of disk space may cause a performance issue in the instance.
In this approach, `SmartLogCleaner` provides a way to clean up the directories which belong to nodes that are not attached anymore to Jenkins.
> [JENKINS-50297] WinSW logs not being cleaned up for cloud-provisioned (ephemeral) agents

- src/main/java/com/cloudbees/jenkins/support/impl/JVMProcessSystemMetricsContents.java
- src/main/java/com/cloudbees/jenkins/support/impl/ProcFilesRetriever.java
- src/main/java/com/cloudbees/jenkins/support/impl/SystemConfiguration.java
"Master JVM porcess system metrics" and "Agent system configuration"
components were only split in label. So all the files were included
twice. The node list to extract proc info from is abstracted. The
components are update to provide only the nodes from which data must
be collected.
> JENKINS-56190 - Only include the proc files that has to be included.

- src/main/java/com/cloudbees/jenkins/support/util/Markdown.java
See [JENKINS-57602](https://issues.jenkins-ci.org/browse/JENKINS-57602)
It doesn't deserve more effort, it's usual to have problems while gathering the data.
Avoid an NPE message in the logs.
And a not used import.
Changelog:
* Avoid an extra message in the log
> [JENKINS-57602] Check null strings to avoid a message in the log

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/api/FileContent.java
- src/test/java/com/cloudbees/jenkins/support/SupportPluginTest.java
[JENKINS-58393](https://issues.jenkins-ci.org/browse/JENKINS-58393): An exception may be thrown when doing a `getTime()` but is not caught in the loop on contents.
> [JENKINS-58393] Catch exception thrown by getTime()

- pom.xml
[JENKINS-47449](https://issues.jenkins-ci.org/browse/JENKINS-47449): Bump the version of the metrics plugin to remove transitive dependency on `com.google.code.findbugs:jsr305`
cc  @jtnord
> [JENKINS-47449] Update version of metrics plugin to cleanup dependencies

- src/main/java/com/cloudbees/jenkins/support/api/BaseFileContent.java
- src/main/java/com/cloudbees/jenkins/support/api/FileContent.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponentTest.java
At least once, I observed a pair of exceptions from the system log of CloudBees Core while it was starting up. I believe this was due to `queue.xml` being deleted at some random time during the bundle write.
```
… com.cloudbees.jenkins.support.api.FileContent lambda$createBaseFileContent$0
WARNING: Error opening file /var/jenkins_home/queue.xml
java.io.FileNotFoundException: File '/var/jenkins_home/queue.xml' does not exist
at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:297)
at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1805)
at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1838)
at com.cloudbees.jenkins.support.configfiles.SecretHandler.findSecrets(SecretHandler.java:96)
at …
```
> More gracefully handle a configuration file deleted while the bundle is being written

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
I have noticed that managed masters in CloudBees Core can be unexpectedly slow to start, and thread dumps often implicate automatic support bundle capture. It seems this happens within ~7s of Jenkins starting up, during which time lots of stuff is still being initialized, so attempting to browse the web UI can be quite slow as Jelly compilation competes with background support file writing often of hundreds of Kib of content. Better to defer this for a few minutes until Jenkins is comfortably up and running.
Workaround: `-Dcom.cloudbees.jenkins.support.SupportPlugin.AUTO_BUNDLE_PERIOD_HOURS=0`
> Avoid capturing an automatic bundle immediately after startup

- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
While investigating some activity in the last few seconds before the Jenkins JVM exits, I noticed that some log messages were getting lost. This patch seems to fix it.
> LogFlusher should run before shutting down Jenkins

- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
- src/test/java/com/cloudbees/jenkins/support/impl/GCLogsTest.java
[JENKINS-58980](https://issues.jenkins-ci.org/browse/JENKINS-58980): Limit the number of GC logs to include in the support bundle, keeping only the latest ones.
* By default, discard GC logs files older than 2 days (last modified date)
* Ability to change / disable this behavior via a system property `com.cloudbees.jenkins.support.impl.GCLogs.retention` accepting a value in days
> [JENKINS-58980] Only include latest GC logs

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
* The pinned/unpinned feature is not used in Jenkins 2.x
* Core always returns unpinned
* It makes the active.txt incompatible with downstream tools.
> [JENKINS-59714] Remove the pinned/unpinned information

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/filter/ContentFilters.java
- src/main/java/com/cloudbees/jenkins/support/timer/DeadlockTrackChecker.java
[JENKINS-59696](https://issues.jenkins-ci.org/browse/JENKINS-59696): This should fix the dynamic loading issues we encounter. The main fix is what has been done in the `DeadlockTrackChecker`. 
Note: Based on my findings, the use of `GlobalConfiguration.all().get(ContentFilters.class)` instead of `ExtensionList.lookupSingleton(ContentFilters.class)` seems to be general workaround to prevent loading the extension twice.
@MRamonLeon @jglick
> [JENKINS-59696] Fix ContentFilters dynamic loading issue

- src/main/java/com/cloudbees/jenkins/support/filter/FilteredConstants.java
- src/main/java/com/cloudbees/jenkins/support/util/StreamUtils.java
- src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
- src/test/java/com/cloudbees/jenkins/support/util/OutputStreamSelectorTest.java
- src/test/java/com/cloudbees/jenkins/support/util/StreamUtilsTest.java
[JENKINS-59455](https://issues.jenkins-ci.org/browse/JENKINS-59455)
- Use the first available env variable, and not path, to be sure it's available.
- Wait for the created agent to be online.
- Consider '\0' (NUL character) as a character that appears to mark the end of a line, and so it must not make files containing it to be considered as binary files.
> Fix the checking of env vars using an existing env var instead of path

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
Fixes [JENKINS-60805](https://issues.jenkins-ci.org/browse/JENKINS-60805) by reverting the signature of the API that was changed in 2.66.
> [JENKINS-60805] Restore binary compatibility

- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
- src/test/java/com/cloudbees/jenkins/support/SupportTestUtils.java
- src/test/java/com/cloudbees/jenkins/support/impl/GCLogsTest.java
[JENKINS-60009](https://issues.jenkins-ci.org/projects/JENKINS/issues/JENKINS-60009): The java arguments to enable GC logs are different since Java9. This PR adds support for it, see also https://docs.oracle.com/javase/9/tools/java.htm#GUID-BE93ABDC-999C-4CB5-A88B-1994AAAC74D5__CONVERTGCLOGGINGFLAGSTOXLOG-A5046BD1.
In order to write tests for this, we need to have tests that execute in JDK 8 or older and tests that execute in JDK 9 or later. So I used the `org.junit.Assume` for this.
Note: Since the 2.164.1 LTS, there is a class [jenkins.utils.java.JavaUtils](https://github.com/jenkinsci/jenkins/commit/412da254f2bbac386e9ab736684140cf107a3ffd#diff-f820412d63e84d362e303aeaa8be7729) that can be used to check if the runtime version is older than 8 or not. But I did not want to raise the …
> [JENKINS-60009] Add support for Java 9 and later for GCLogs

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/java/com/cloudbees/jenkins/support/api/Component.java
- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
See [JENKINS-61659](https://issues.jenkins-ci.org/browse/JENKINS-61659)
* Expose components through api
* New endpoint generating a support bundle only with included components
> [JENKINS-61659] Allow to generate custom support bundle through api

- src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
Used only by Jenkins core 2.226+
Ref:
* https://jenkins.io/changelog/#v2.226
* jenkinsci/jenkins#4546
I hesitated between SECURITY and TROUBLESHOOTING categories but I think that the security concern of this feature is more important
> Name of the category for this management link

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/cloudbees/jenkins/support/filter/ContentFilters.java
- src/test/java/com/cloudbees/jenkins/support/CasCTest.java
- src/test/java/com/cloudbees/jenkins/support/filter/ContentMappingsTest.java
- src/test/resources/com/cloudbees/jenkins/support/configuration-as-code.yaml
See: https://issues.jenkins-ci.org/browse/JENKINS-61796
Add a test for JCasC configuration and set the section of the plugin under the security group, to match the group where it will land when https://github.com/jenkinsci/support-core-plugin/pull/211 is merged
The new place on UI:
> [JENKINS-61796] JCasC test and configuration section

- src/test/java/com/cloudbees/jenkins/support/BundleNamePrefixTest.java
- src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponentTest.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/SecretHandlerTest.java
- src/test/java/com/cloudbees/jenkins/support/filter/InetAddressContentFilterTest.java
- src/test/java/com/cloudbees/jenkins/support/filter/SensitiveContentFilterTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/AgentProtocolsTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/NetworkInterfacesTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/ReverseProxyTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/SlaveCommandStatisticsTest.java
- src/test/java/com/cloudbees/jenkins/support/slowrequest/InflightRequestTest.java
I have see many different variants like `j`, `r`, `rule`, `jenkins` and `jenkinsRule` among different Jenkins related repositories. `j` seems to be the most common one. Therefore adapting the tests here that used a different variant so far.
> Test improvement - Consistent naming of JenkinsRule variable

- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
- src/test/java/com/cloudbees/jenkins/support/actions/SupportAbstractItemActionTest.java
- src/test/java/com/cloudbees/jenkins/support/actions/SupportComputerActionTest.java
- src/test/java/com/cloudbees/jenkins/support/actions/SupportRunActionTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/AbstractItemComponentTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/NodeRemoteDirectoryComponentTest.java
The usage in test methods here often did not meet some Javadoc requirements, therefore generating a lot of warnings when running `mvn javadoc:test-javadoc`.
> Test improvement - Remove non-required Javadoc on test methods

- src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/OtherLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/TaskLogs.java
- src/test/java/com/cloudbees/jenkins/support/impl/CustomLogsTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/JenkinsLogsTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/OtherLogsTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/TaskLogsTest.java
[JENKINS-62526](https://issues.jenkins-ci.org/browse/JENKINS-62526) Split the "Master Log Recorders" that was taking files from many location (`$JENKINS_HOME/`, `$JENKINS_HOME/logs`, `$JENKINS_HOME/logs/custom`, `$JENKINS_HOME/support`) and generated by different components.
Proposal:
* "Master Log Recorders": 
* collect Jenkins logs
* store under `nodes/master/logs/` in the bundle
* selected by default
* "Master Custom Log Recorders":
* collect Logs recorders defined by a user
* store under `nodes/master/logs/custom/` in the bundle
* selected by default
* "Master Task Log Recorders": selected by default
* collect Jenkins Tasks logs
* store under `task-logs/` in the bundle
* selected by default
* "Master Other Log Recorders": 
* collect Logs under `$JENKINS_HOME`
* store under …
> [JENKINS-62526] Split JenkinsLogs

- src/main/java/com/cloudbees/jenkins/support/impl/LogFilenameAgentFilter.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
When there is a big quantity of agents and there are a lot of logs on these agents, the agent's log folder could take more than 600MB of space. This means the Jenkins master might suffer from performance issues while compressing.
The main issue here is that we are capturing logs in the agents even of those who are 1 year old, which does not make a lot of sense in the troubleshooting.
Given this situation, the support-core should not grab from the agent the log files which are very old
Example of what is happening in a real case for a specific agent.
```
2.0M	jenkins-slave.0.err.log
2.0M	jenkins-slave.1.err.log
2.0M	jenkins-slave.2.err.log
2.0M	jenkins-slave.3.err.log
2.0M	jenkins-slave.4.err.log
2.0M	jenkins-slave.5.err.log
2.0M	jenkins-slave.6.err.log
2.0M	jenkins-slave.7.err.log
1.2M …
```
> [JENKINS-63635] Retrieve recent agent logs

- pom.xml
- src/main/resources/com/cloudbees/jenkins/support/actions/SupportAbstractItemAction/index.jelly
- src/main/resources/com/cloudbees/jenkins/support/actions/SupportComputerAction/index.jelly
- src/main/resources/com/cloudbees/jenkins/support/actions/SupportRunAction/index.jelly
- src/test/java/com/cloudbees/jenkins/support/actions/SupportAbstractItemActionTest.java
When generating support bundle for items and nodes, make sure
that sidepanel of the current item is rendered, not the Jenkins one.
> Render current item's sidepanel instead of the Jenkins one

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/resources/com/cloudbees/jenkins/support/Messages.properties
- src/main/resources/com/cloudbees/jenkins/support/SupportAction/index.jelly
- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
Initial approach which add a new `Download` button in the `Existing support bundles` section which allows:
- Download one single file
- Download multiple files grouping all of the them in a single zip file (multiBundle(n).zip) where n is the number of files zipped)
This is how it looks the UI
> [JENKINS-35342] Allow to download a bundle

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/java/com/cloudbees/jenkins/support/SupportCommand.java
- src/main/java/com/cloudbees/jenkins/support/impl/JVMProcessSystemMetricsContents.java
- src/main/java/com/cloudbees/jenkins/support/impl/SystemConfiguration.java
- src/main/resources/com/cloudbees/jenkins/support/Messages.properties
- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
- src/test/java/com/cloudbees/jenkins/support/SupportPluginTest.java
[JENKINS-63722](https://issues.jenkins-ci.org/browse/JENKINS-63722) Fixing this by overriding `getId()`. We are also adding a `WARNING` for the different REST APIs and make sure that the old IDs `Master` and `Agents` are still working identically.
> [JENKINS-63722] Fix getId() of nested components

- src/main/java/com/cloudbees/jenkins/support/BundleFileName.java
- src/main/java/com/cloudbees/jenkins/support/BundleNameInstanceTypeProvider.java
- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/java/com/cloudbees/jenkins/support/SupportCommand.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/actions/SupportAbstractItemAction.java
- src/main/java/com/cloudbees/jenkins/support/actions/SupportComputerAction.java
- src/main/java/com/cloudbees/jenkins/support/actions/SupportObjectAction.java
- src/main/java/com/cloudbees/jenkins/support/actions/SupportRunAction.java
- src/main/resources/com/cloudbees/jenkins/support/actions/Messages.properties
- src/test/java/com/cloudbees/jenkins/support/BundleFileNameTest.java
- src/test/java/com/cloudbees/jenkins/support/BundleNamePrefixTest.java
To avoid confusion include the name of the Object for which support bundle is generated into the action naem.
> JENKINS-64172: Support Action names are made distinct

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/util/IgnoreCloseOutputStream.java
See the Jira for all the details https://issues.jenkins.io/browse/JENKINS-64401
Basically, there is a performance issue which happens for all support bundles generated when {{$JENKINS_HOME/logs/tasks/}} have big text files (you can reproduce the issue with around 6 files bigger than 50 MB each of them).
The current proposal is to use {{BufferedOutputStream}} instead of {{FilterOutputStream}} as stream so we can write bytes to the underlying output stream without necessarily causing a call to the underlying system for each byte written. 
In my example, without the fix, a support bundle with the issue exposed is taking around 15 minutes to be generated. With the current implementation, the support bundle is generated in less than 20 seconds.
> [FIXED JENKINS-64601] Improve write performance for big files under $JENKINS_HOME/logs/tasks/ by using BufferedOutputStream instead of OutputStream

- src/test/java/com/cloudbees/jenkins/support/BundleNamePrefixTest.java
The format is wrong. It should be "yyyy" instead of "YYYY". "YYYY" stands for the week year, not the year, which makes the latest week of the year this test is failing (see https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html)
Thanks Thierry Wasylczenko for getting the root cause of the issue.
> Update year format for BundleNamePrefixTest

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
There is a Support Core component which takes 5 seconds to startup on my instance. 
This change captures startup performance when Jenkins core flags are set.
> Log startup performance of Support Core components

- src/main/java/com/cloudbees/jenkins/support/impl/ReverseProxy.java
- src/test/java/com/cloudbees/jenkins/support/impl/ReverseProxyTest.java
Presence of the standard `Forwarded` header and the rest of non-standard headers are added:
- `X-Forwarded-Proto`
- `X-Forwarded-Host`
- `X-Forwarded-Port`
> JENKINS-64667 - Check for more reverse proxy headers

- src/main/java/com/cloudbees/jenkins/support/AsyncResultCache.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
- src/main/java/com/cloudbees/jenkins/support/util/CallAsyncWrapper.java
Create a wrapper to make `Channel.callAsync` really async. The problem is that `callAsync` is performing a remoting call before returning the Future, so the call is not really async - see https://github.com/jenkinsci/remoting/blob/remoting-4.6/src/main/java/hudson/remoting/Request.java#L238 
This PR should fix both Jira issues below:
* https://issues.jenkins-ci.org/browse/JENKINS-42011 
* https://issues.jenkins.io/browse/JENKINS-42012
> [JENKINS-42012] Wrapper to make Channel.callAsync really async

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
[JENKINS-65097](https://issues.jenkins.io/browse/JENKINS-65097): Add a field to Nodes with JNLPLauncher, whether they use Websocket or no. This requires to update the Core dependency to 2.222 (see https://github.com/jenkinsci/jenkins/commit/5b5040298f5fbf9d5ff7ea7fbfd34f7169e94d75)
> [JENKINS-65097] Add information about websocket in nodes.md

- pom.xml
Revert the change to version 1.9.40.0 proposed by dependabot in https://github.com/jenkinsci/support-core-plugin/pull/275 that is an old branch of the async-http-plugin and use the latest 1.7.24.3 instead.
> Revert #275 and update async-http-client update to 1.7.24.3

- pom.xml
Bump to 2.222.x to match the Jenkins version requirement. Need to stick with version 10 unless we move to baseline 2.222.4.
Also removed the dependency version that are already in the bom. Should supersede https://github.com/jenkinsci/support-core-plugin/pull/274.
> Cleanup pom for bom-2.222.x

- pom.xml
- src/test/java/com/cloudbees/jenkins/support/impl/GCLogsTest.java
[JENKINS-64549](https://issues.jenkins.io/browse/JENKINS-64549) Upgrade to Mockito is failing on the mock of a static inner class. Switching to PowerMockito and the version managed in plugin-pom.
Amends https://github.com/jenkinsci/support-core-plugin/pull/262
> [JENKINS-64549] Use PowerMockito and versions from plugin-pom

- src/main/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitors.java
- src/test/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitorsTest.java
[JENKINS-64547](https://issues.jenkins.io/browse/JENKINS-64547):
* Check if the monitor is enabled first, if not then stop there
* Refactor the `AdministrativeMonitors` with java 8 /lambda expressions
* Add a test for the component
> [JENKINS-64547] AdministrativeMonitors should stop if a monitor is disabled

- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
- src/test/java/com/cloudbees/jenkins/support/SupportTestUtils.java
- src/test/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogsTest.java
[JENKINS-66002](https://issues.jenkins.io/browse/JENKINS-66002): Recover the Agent Launch Logs component that was mistakenly removed in support-core:2.33 by https://github.com/jenkinsci/support-core-plugin/commit/8ce4b3baf504f834ae421e8095532188bbd92e3a#diff-6208542ddc2fa48456c666e0478afaefcc2ff037fa1f94cb7b5c1f51bc224e22. But also:
* Adjust the retention of files collected to 7 days instead of 1 year
* Do not select the component by default (nobody reported this for years so I do not think this should be selected by default)
****
> [JENKINS-66002] Recover Agent Launch Logs component

- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/OtherLogs.java
- src/test/java/com/cloudbees/jenkins/support/impl/OtherLogsTest.java
[JENKINS-60010](https://issues.jenkins.io/browse/JENKINS-60010):
* made GCLogs#isGcLogRotationConfigured and GCLogs#getGcLogFileLocation public
* Filter out GC Logs from Other Logs component if the GC Logs are configured for the JVM
> [JENKINS-60010] OtherLogs should not include GC Logs if activated with the JVM

- README.md
- src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
- src/test/java/com/cloudbees/jenkins/support/filter/ContentMappingsTest.java
- src/test/resources/com/cloudbees/jenkins/support/filter/ContentMappingsTest/additionalStopWordsIncludedAsStopWord/support/additional-stop-words.txt
[JENKINS-66023](https://issues.jenkins.io/browse/JENKINS-66023): Add a feature to provide additional stop words from a text file `$JENKINS_HOME/support/additional-stop-words.txt`. Location is overridable via System Property `com.cloudbees.jenkins.support.filter.ContentMappings.additionalStopWordsFile`.
> [JENKINS-66023] Ability to provide additional Stop Words

- src/test/java/com/cloudbees/jenkins/support/filter/ContentMappingsTest.java
[ContentMappingsTest.contentMappingsOrderedByLengthDescending](https://github.com/jenkinsci/support-core-plugin/blob/65773ad5ce2327b6802738f493f2395772940a12/src/test/java/com/cloudbees/jenkins/support/filter/ContentMappingsTest.java#L90) fails under Jenkins 2.307+ due to https://github.com/jenkinsci/jenkins/pull/5425
The unit test now fails because additional content mappings are added: `Built-in Node` and `built-in`
cc @MRamonLeon @rsandell @Dohbedoh
> make unit test compatible with jenkins 2.307+

- pom.xml
- src/test/java/com/cloudbees/jenkins/support/impl/GCLogsTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/OtherLogsTest.java
* Removed Powermock that is currently breaking CI and also learnt from https://github.com/jenkinsci/jenkins/pull/5736 that it is not straightforward to make it work in Java 17 and is unmaintained. We can do everything with Mockito.
* Applied checkstyles
> [chore] Remove powermock that breaks CI

- pom.xml
This removes
```
1) Error injecting constructor,
java.lang.reflect.InaccessibleObjectException: Unable to make public
long
com.sun.management.internal.OperatingSystemImpl.getProcessCpuTime()
accessible: module jdk.management does not "opens
com.sun.management.internal" to unnamed module @7fd4acee
at
jenkins.metrics.impl.VMMetricProviderImpl.<init>(VMMetricProviderImpl.java:56)
```
as recent metrics plugin doesn't rely on this private method as of
https://github.com/jenkinsci/metrics-plugin/pull/42
This was also causing flakes when running tests on jdk11 because of https://github.com/jenkinsci/support-core-plugin/blob/2f2dbb41d3be70a42c588f05921eddb1f72b0ee8/src/test/java/com/cloudbees/jenkins/support/SupportTestUtils.java#L192
> Update BOM and metrics plugin to fix test warnings on jdk11

- src/main/java/com/cloudbees/jenkins/support/impl/NetworkInterfaces.java
- src/test/java/com/cloudbees/jenkins/support/impl/NetworkInterfacesTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/OtherLogsTest.java
Gathering NetworkInterfaces would reliable timeout when runnign locally for the Jenkins controller on windows with a large (but somewhat standard) number of NICs.
on my laptop with 58 NICs in the enumeration (filter drivers, hyper-v....) it took over 900ms to just run the code in the `call` method which is longer than the `500`ms allowed for the callable to complete.
Subsequent to this change the callable code now completes in ~390ms on the same machine.
This caused the test to reliably fail (and is a little flaky in CI also) so restructured the code to build the individual NIC strings in parallel.
At the same time I removed some gratuitous use of static mocking in a test class.
> more performant nic gatherer and falky test improvements

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
Reviewing a support bundle, I saw that the main system log was filled with noise about K8s agents of the form
```
…	WARNING	c.c.j.support.SupportPlugin#writeBundle: Could not attach ''nodes/slave/… to support bundle
java.nio.channels.ClosedChannelException
at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:238)
at …
at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:340)
at hudson.remoting.Channel.close(Channel.java:1501)
at hudson.remoting.Channel.close(Channel.java:1454)
at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:887)
at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:853)
at …
```
> Noisy warnings from `SupportPlugin.writeBundle` about `ChannelClosedException`

- src/main/java/com/cloudbees/jenkins/support/config/SupportPluginManagement.java
Quick fix of a warning in CI:
```
17:39:22  [WARNING] Javadoc Warnings
17:39:22  [WARNING] /home/jenkins/workspace/ugins_support-core-plugin_master/src/main/java/com/cloudbees/jenkins/support/config/SupportPluginManagement.java:158: warning: no description for @return
17:39:22  [WARNING] * @return
17:39:22  [WARNING] ^
```
> [chore] Fix javadoc warning in SupportPluginManagement

- Jenkinsfile
Addresses the warning:
```
WARNING: Ignoring deprecated "javaLevel" parameter. This parameter should be removed from your "Jenkinsfile".
```
> [chore] Remove deprecated javaLevel from Jenkinsfile

- src/test/java/com/cloudbees/jenkins/support/impl/ReverseProxyTest.java
- src/test/java/com/cloudbees/jenkins/support/util/IgnoreCloseOutputStreamTest.java
- src/test/java/com/cloudbees/jenkins/support/util/IgnoreCloseWriterTest.java
Remove deprecated usage of MockitoJUnitRunner. Should allow to update latest plugin-pom dep https://github.com/jenkinsci/support-core-plugin/pull/318
> [chore] Remove deprecated usage of MockitoJUnitRunner

- src/main/java/com/cloudbees/jenkins/support/SupportLogHandler.java
As discovered in https://github.com/jenkinsci/bom/pull/644#issuecomment-985156639 it seems that the ring buffer could hold a strong ref to `LogRecord.parameters` for recently logged messages, including things like
```
FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpLoader: ignoring org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxResolvingClassLoader@…
```
which really ought to have been collected.
Eagerly formatting the records is not a good option for these sub-`INFO` messages which might otherwise never be formatted, so the most straightforward fix seems to be to use `SoftReference` to offer these records most of the time to https://github.com/jenkinsci/support-core-plugin/blob/bb61a87442c7d5ea391214bd97cd71edb422e8d7/src/main/java/com/cloudbees/jenkins/support/SupportLogHandler.jav …
> `SupportLogHandler.records` could leak memory

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
Currently this page can list dozens of existing support bundles, in totally random order, making it very hard to find (for example) the most recent one, or one taken just before some known outage.
> [JENKINS-64558] Sort existing bundles in `/support/`

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
- src/test/java/com/cloudbees/jenkins/support/impl/CustomLogsTest.java
There is some issues on migration code from https://github.com/jenkinsci/jenkins/pull/4538 see https://github.com/jenkinsci/github-branch-source-plugin/pull/485 for full details.
This PR updates the plugin usages of affected code to make it work again and updates the baseline. Issues can be demonstrated by `mvn test -Djenkins.version=2.332.1-cb-3 -Dtest=CustomLogsTest#testCustomLogsContent -Denforcer.skip -Daccess-modifier-checker.skip`
> Fix LogRecorder usage for newer core versions

- src/main/java/com/cloudbees/jenkins/support/impl/TaskLogs.java
- src/main/java/com/cloudbees/jenkins/support/timer/FileListCapComponent.java
- src/main/java/com/cloudbees/jenkins/support/timer/UnfilteredFileListCapComponent.java
Was frustrated to look through a support bundle containing lots of file entries dating as far back as 2018:
* `deadlocks/DeadlockDetected-20181128-124111.txt`
* `task-logs/cloudbees-devoptics-deliver-authentication.log`
Also sorting these files for legibility.
**Untested.**
> Skip old log files

- src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
- src/test/java/com/cloudbees/jenkins/support/impl/GCLogsTest.java
[JENKINS-67940](https://issues.jenkins.io/browse/JENKINS-67940)
Log rotation in JDK9+ with Xlog:gc is enabled by default and only disabled if `filecount=0` is set. The GCLogs component was missing that point and did not collect rotated gc logs. Only parameterized ones.
> [JENKINS-67940] Fix retrieval of rotated JDK 9+ GC logs

- src/main/java/com/cloudbees/jenkins/support/slowrequest/InflightRequest.java
Noticed in a thread dump:
```
"Handling POST /…/ajaxExecutors from … : Jetty (winstone)-…" Id=… Group=main RUNNABLE
at java.util.regex.Pattern$CharProperty.match(Pattern.java:3791)
at java.util.regex.Pattern$Curly.match0(Pattern.java:4274)
at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
at java.util.regex.Pattern$Start.match(Pattern.java:3475)
at java.util.regex.Matcher.search(Matcher.java:1248)
at java.util.regex.Matcher.find(Matcher.java:637)
at net.sf.uadetector.parser.AbstractUserAgentStringParser.examineOperatingSystem(AbstractUserAgentStringParser.java:167)
at net.sf.uadetector.parser.AbstractUserAgentStringParser.parse(AbstractUserAgentStringParser.java:205)
at net.sf.uadetector.parser.AbstractUserAgentStringParser.parse(AbstractUserAgentStringParser.java:39)
at …
```
> `InflightRequest` should only parse `userAgent` if and when `SlowRequestChecker` needs it

- src/main/java/com/cloudbees/jenkins/support/impl/UpdateCenter.java
A few deprecated API usages are updated.
Id of every update site is printed alongside the information that is already available. It should make it easier to correlate logs that mention update site id to the URL of the site.
- ~[ ] Link to relevant issues in GitHub or Jira~
- ~[ ] Link to relevant pull requests, esp. upstream and downstream changes~
> Update Site Id is added to Update Center component

- src/test/java/com/cloudbees/jenkins/support/impl/TaskLogsTest.java
This test is not necessary and may break if a timer tasks has already done something before the component is actually invoked..
```
java.lang.AssertionError: Should not write anything
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at com.cloudbees.jenkins.support.impl.TaskLogsTest.testTaskLogsContentEmpty(TaskLogsTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at …
```
> [chore] Remove unnecessary flaky test

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/impl/UpdateCenter.java
- src/test/java/com/cloudbees/jenkins/support/impl/UpdateCenterTest.java
[JENKINS-68008](https://issues.jenkins.io/browse/JENKINS-68008) The AyncHttpClient plugin is not necessary and can be removed.
> [JENKINS-68008] Remove unnecessary usage of AHCUtils

- pom.xml
In https://github.com/jenkinsci/bom/pull/935 I have been trying to test this plugin with Java 17, which requires setting `argLine` to include some `--add-opens` directives, but this plugin rather unhelpfully wipes them out to set its own `argLine`. This PR changes the POM to use `systemPropertyVariables` rather than wiping out `argLine`. With this change I can successfully test on Java 11.
As a bonus, I also incrementalified the plugin and updated the Jenkins version and plugin BOM. This should help me more easily consume this build from https://github.com/jenkinsci/bom/pull/935.
> Use `systemPropertyVariables` rather than `argLine`

- src/test/java/com/cloudbees/jenkins/support/SupportTestUtils.java
Required for https://github.com/jenkinsci/bom/pull/955 and https://github.com/jenkinsci/bom/pull/960
Can we get a release please?
> PCT: Adapt test for 2.340 structure changes

- pom.xml
Supersedes #358. Downstream of https://github.com/jenkinsci/metrics-plugin/pull/153. Getting this released will help us cross the recent `jackson2-api` flag day and restore `support-core` to jenkinsci/bom as described in https://github.com/jenkinsci/bom/pull/1011, https://github.com/jenkinsci/metrics-plugin/pull/153, and https://github.com/jenkinsci/bom/pull/1016.
CC @jetersen @Dohbedoh
> Update plugin parent POM and plugin BOM

- src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
As an alternative to #362, ignore this flaky test.
> Ignore flaky test

- Jenkinsfile
- src/main/java/com/cloudbees/jenkins/support/AsyncResultCache.java
- src/main/java/com/cloudbees/jenkins/support/filter/InetAddressContentFilter.java
- src/test/java/com/cloudbees/jenkins/support/filter/InetAddressContentFilterTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
[JENKINS-68339](https://issues.jenkins.io/browse/JENKINS-68339)
* Only use `channel.callAsync` (through the `CallAsyncWrapper`) if retrieving data on remote node. When retrieving data on the built-in node, just execute the callable.
* updated CI to build use containers, and build on JDK 11 and JDK 17.
I am hoping that this fix the flakyness with JDK 17 as we remove the remoting overhead for this use case. See the following for reference:
* https://github.com/jenkinsci/support-core-plugin/pull/363
* https://github.com/jenkinsci/support-core-plugin/pull/362
> [JENKINS-68339] Skip remoting stack on built-in node and improve IPv6 Regex

- src/main/java/com/cloudbees/jenkins/support/SupportLogHandler.java
Essentially reverting #324 (slight simpification to timing of `format` in the process). Essentially the same fix as https://github.com/jenkinsci/jenkins/pull/6643. ~Here the calculus is simpler since any log records appearing in the handler _will_ need to be formatted (we write them to disk files) so there is no justification for deferring the message format expansion.~
Testing in `pipeline-groovy-lib-plugin`:
<details>
```diff
diff --git pom.xml pom.xml
index 9ee4e40..98f9e92 100644
--- pom.xml
+++ pom.xml
@@ -63,15 +63,15 @@
</pluginRepositories>
<properties>
<changelist>999999-SNAPSHOT</changelist>
-        <jenkins.version>2.289.1</jenkins.version>
+        <jenkins.version>2.355-SNAPSHOT</jenkins.version> 
<gitHubRepo>jenkinsci/${project.artifactId}-plugin</gitHubRepo>
</properties> …
```
> [JENKINS-68417] Revert `LogRecord` tricks

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
[JENKINS-68743](https://issues.jenkins.io/browse/JENKINS-68743) Report if a node is marked offline. 
Note [Computer.java#isTemporarilyOffline](https://github.com/jenkinsci/jenkins/blob/jenkins-2.332.3/core/src/main/java/hudson/model/Computer.java#L667-L684) is marked as deprecated to warn people that they should use `Computer#isOffline` to truly know about a node status. What we want to know here is if that `temporarilyOffline` attribute is set to `true` for troubleshooting purposes.
> [JENKINS-68743] Report if a node is marked offline

- src/test/java/com/cloudbees/jenkins/support/impl/AbstractItemComponentTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/RunDirectoryComponentTest.java
Observed in https://github.com/jenkinsci/bom/pull/1407: `com.cloudbees.jenkins.support.impl.AbstractItemComponentTest.addContentsFromPipeline` and `com.cloudbees.jenkins.support.impl.RunDirectoryComponentTest.addContentsFromPipeline` started failing with:
- https://ci.jenkins.io/job/Tools/job/bom/view/change-requests/job/PR-1407/1/testReport/junit/com.cloudbees.jenkins.support.impl/AbstractItemComponentTest/pct_support_core_weekly___addContentsFromPipeline/
- https://ci.jenkins.io/job/Tools/job/bom/view/change-requests/job/PR-1407/1/testReport/junit/com.cloudbees.jenkins.support.impl/RunDirectoryComponentTest/pct_support_core_weekly___addContentsFromPipeline/
The failure starts occurring after https://github.com/jenkinsci/jenkins/pull/6982, which improves the test framework by making …
> Adapt to jenkinsci/jenkins#6982

- src/main/java/com/cloudbees/jenkins/support/configfiles/AgentsConfigFile.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/AgentsConfigFileTest.java
[JENKINS-66064](https://issues.jenkins.io/browse/JENKINS-66064)
> [JENKINS-66064] Anonymize Agent dir name when collecting Config file

- src/main/java/com/cloudbees/jenkins/support/SupportContextImpl.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/api/Component.java
- src/main/java/com/cloudbees/jenkins/support/api/SupportContext.java
- src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
[JENKINS-70351](https://issues.jenkins.io/browse/JENKINS-70351)
* Removed the `SupportPlugin#postInitialize` that happens on plugin startup
* Deprecate the `SupportContext` that the `SupportPlugin#postInitialize` is setting as it is obsolete / unused since https://github.com/jenkinsci/support-core-plugin/commit/5905c4f2ba026302de91ce629d72c74cd05a8051.
* Add an `@Initializer(after = InitMilestone.EXTENSIONS_AUGMENTED, before = InitMilestone.SYSTEM_CONFIG_LOADED)` to the `CustomLogs.CustomLogHandler`. For some reason, this was done via `Component#start(SupportContext)` though not related to the `SupportContext`.
> [JENKINS-70351] Fix initialization and deprecate obsolete SupportContext

- src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/TaskLogs.java
Cleanup from https://github.com/jenkinsci/support-core-plugin/pull/140#discussion_r177712220.
> Use `SafeTimerTask.getLogsRoot`

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
Observed an NPE caught and reported as _Could not install root log handler…_ which from the stack trace looks like the computer went offline immediately after coming online, perhaps.
> Avoid NPE when `Computer.getNode` returns null

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
- src/main/java/com/cloudbees/jenkins/support/impl/SmartLogCleaner.java
- src/main/java/com/cloudbees/jenkins/support/impl/SmartLogFetcher.java
- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/SmartLogCleanerTest.java
Part of log files generated by support-core plugin are located under `$JENKINS_HOME/logs`. Another part is located under `$JENKINS_HOME/support`. All Jenkins log files should be located under `$JENKINS_HOME/logs`.
`support/all_*.log` are being moved to `logs/support/all_*.log`
This also honors any log root directory override specified by system property via Jenkins core mecanism.
> Jenkins logs should be colocated

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
I observed an error
```
java.util.ConcurrentModificationException
at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
at com.cloudbees.jenkins.support.SupportPlugin.writeBundle(SupportPlugin.java:374)
at com.cloudbees.jenkins.support.SupportPlugin.writeBundle(SupportPlugin.java:330)
at com.cloudbees.jenkins.support.SupportPlugin$PeriodicWorkImpl.lambda$doRun$0(SupportPlugin.java:888)
```
where the line number points to https://github.com/jenkinsci/support-core-plugin/blob/ce1fc0f7dcde645b6454ebaeebfca5e6f8b5695c/src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java#L395 I suppose some component must have called `Container.add` outside the dynamic scope of `Component.addContents` (from …
> Make `ContentContainer.contents` thread-safe

- src/main/java/com/cloudbees/jenkins/support/filter/ContentFilters.java
- src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
- src/main/java/com/cloudbees/jenkins/support/threaddump/HighLoadCpuChecker.java
It came to my attention when looking at some initialization issues recently (such as https://github.com/jenkinsci/job-config-history-plugin/pull/279/files) that we should be using `ExtensionList.[lookup|lookupSingleton]` if we can, for example in the `get()` methods of singleton extensions, instead of the `GlobalConfiguration.all()` | `ManagementLink.all()`.
> Improve initialization of some extensions

- src/main/java/com/cloudbees/jenkins/support/actions/SupportRunAction.java
- src/main/resources/com/cloudbees/jenkins/support/actions/SupportRunAction/index.jelly
[JENKINS-71183](https://issues.jenkins.io/browse/JENKINS-71183): same as https://github.com/jenkinsci/support-core-plugin/pull/326 but for the Run action. 
* Start Jenkins
* Create a Pipeline Job and build it once
* Go to the build page
* Open the "Build Support" link
* Validate that the anonymization warnings says that anonymization is disabled
* Go to Manage Jenkins > Configure Global Security > Support Anonymization and enable it
* Go back to the build page
* Open the "Build Support" link
* Validate that the anonymization message says that anonymization is enabled
> [JENKINS-71183] Fix Build actions anonymization enable UI check

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
In a support bundle (ironically enough) I noticed a stack trace
```
java.util.NoSuchElementException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1513)
at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1534)
at com.cloudbees.jenkins.support.SupportAction.doDownloadBundles(SupportAction.java:227)
```
which looks like it could come from an attempt to download no bundles. Should be handled more clearly.
> More gracefully handle empty `bundlesToDownload`

- src/main/java/com/cloudbees/jenkins/support/api/BaseFileContent.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponentTest.java
Without dropping support for Commons IO 2.11.0, add support for Commons IO 2.12.0 and 2.13.0, which throw `NoSuchFileException` in places where the previous version threw `FileNotFoundException`.
Tested in `jenkinsci/bom` with an incremental build of core with Commons 2.13.0.
> Forward compatibility with Apache Commons IO 2.13.0

- src/main/java/com/cloudbees/jenkins/support/api/BaseFileContent.java
- src/test/java/com/cloudbees/jenkins/support/api/FileContentTest.java
- src/test/resources/com/cloudbees/jenkins/support/api/non-utf8.txt
[JENKINS-71466](https://issues.jenkins.io/browse/JENKINS-71466) Fix issues encoding exception originating from `Files.readAllLines`.
```[tasklist]
```
> [JENKINS-71466] Fix MalformedInputException on non-UTF-8 characters when Anonymization is on

- src/main/java/com/cloudbees/jenkins/support/filter/SensitiveContentFilter.java
- src/test/java/com/cloudbees/jenkins/support/util/WordReplacerTest.java
[JENKINS-71529](https://issues.jenkins.io/browse/JENKINS-71529): `\b` causes a change of behavior and prevent the matching of words that are bound with a non word character. To fix this (as it was working with the previous bahevior of the WordReplacer) we can use negative lookahead and negative lookbehind.
```[tasklist]
```
> [JENKINS-71529] Fix sensitive word boundaries matching

- src/main/java/com/cloudbees/jenkins/support/AsyncResultCache.java
- src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
The test added in #474 has been observed to flake
```
java.lang.AssertionError: 
worked on agent
Expected: a string containing "All open files"
but: was "slave0
======
N/A: Either no connection to node or no cached result
"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at com.cloudbees.jenkins.support.impl.FileDescriptorLimitTest.agentContentFilter(FileDescriptorLimitTest.java:92)
```
with nothing obviously wrong in stdout/stderr: the agent does come online.
> Diagnostics for flake in `FileDescriptorLimitTest.agentContentFilter`

- src/main/java/com/cloudbees/jenkins/support/impl/NodeExecutors.java
- src/test/java/com/cloudbees/jenkins/support/impl/NodeExecutorsTest.java
[JENKINS-71732](https://issues.jenkins.io/browse/JENKINS-71732): when recently troubleshooting issue with pipeline execution leaks on heavyweight executors (https://issues.jenkins.io/browse/JENKINS-71692), I found it hard to get information about the state of the executor and what was running on it from a Support Bundle. And other components such as thread dumps / pipeline thread dumps did not help either... So proposing a component that dumps the node executors details (not selected by default).
* Generate a Support Bundle with the "Node Executors" component selected:
```
Nodes Executors
===========
* built-in (Jenkins)
- Executor #-1
- active: true
- busy: true
- causesOfInterruption: []
- currentWorkUnit: hudson.model.queue.WorkUnit@5497813c[work=item_visible_omission » …
```
> [JENKINS-71732] Add component to collect executors information

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfiguration.java
- src/main/resources/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfiguration/config.jelly
- src/main/resources/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfiguration/config.properties
- src/main/resources/com/cloudbees/jenkins/support/config/SupportPluginManagement/index.jelly
- src/test/java/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfigurationSystemPropertiesTest.java
- src/test/java/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfigurationTest.java
[JENKINS-71722](https://issues.jenkins.io/browse/JENKINS-71722): global configuration (disablement and period) was not respected in the periodic generation. 
* Start Jenkins
* Configure a recurrence period of 2 hours
* Validate that periodic generation happens every 2 hours
```[tasklist]
```
> [JENKINS-71722][JENKINS-71758] Respect globally configured period for Periodic generation

- src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
Continuing #483. Observed a flake again
```
java.lang.AssertionError: 
worked on agent
Expected: a string containing "All open files"
but: was "slave0
======
N/A: Either no connection to node or no cached result
"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at com.cloudbees.jenkins.support.impl.FileDescriptorLimitTest.agentContentFilter(FileDescriptorLimitTest.java:99)
```
No obvious explanation in controller logs other than that the channel seems to be closed by this point:
```
…
1.363 [id=134]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
1.417 [id=115]	INFO	o.jvnet.hudson.test.JenkinsRule#waitOnline: Launching slave0…
2.479 [id=67]	INFO	o.j.h.test.SimpleCommandLauncher#launch: agent launched for slave0
2.480 [id=115]	INFO …
```
> More diagnostics for `FileDescriptorLimitTest` flake

- src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
This continues to fail occasionally in PCT and as noted in https://github.com/jenkinsci/support-core-plugin/pull/486#issuecomment-1679167658 I have run out of ideas for diagnosing it properly.
> Giving up on flake in `FileDescriptorLimitTest.agentContentFilter`

- src/test/java/com/cloudbees/jenkins/support/actions/SupportAbstractItemActionTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/AbstractItemComponentTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/RunDirectoryComponentTest.java
As of https://github.com/jenkinsci/workflow-cps-plugin/pull/807, `BulkFlowNodeStorage` will be used by default for completed Pipelines, and the flow node data will be stored in a single file in a `/workflow-completed` directory, not as individual files in `/workflow`, so various test assertions in this plugin need to be modified.
I tested this manually against `workflow-cps` [3806.va_3a_6988277b_2](https://github.com/jenkinsci/workflow-cps-plugin/releases/tag/3806.va_3a_6988277b_2), but consuming that here requires both Jenkins minimum version updates and BOM updates, so I left those changes out here.
```[tasklist]
```
> Modify Pipeline-related test assertions to not assume that `SimpleXStreamFlowNodeStorage` is being used

- src/main/java/com/cloudbees/jenkins/support/impl/NodeExecutors.java
- src/main/java/com/cloudbees/jenkins/support/impl/NodeMonitors.java
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
Seemed to make more sense to me. Noticed while doing #496.
> Switching from `ComponentCategory.CONTROLLER` to `AGENT` in a couple of cases

- pom.xml
This library has been provided by core for a long time.
> Stop bundling SLF4J JAR file

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/api/BaseFileContent.java
- src/main/java/com/cloudbees/jenkins/support/api/FileContent.java
- src/main/java/com/cloudbees/jenkins/support/api/PrefilteredPrintedContent.java
- src/main/java/com/cloudbees/jenkins/support/api/StringContent.java
- src/main/java/com/cloudbees/jenkins/support/filter/AllContentFilters.java
- src/main/java/com/cloudbees/jenkins/support/filter/ContentFilter.java
- src/main/java/com/cloudbees/jenkins/support/filter/NoneFilter.java
- src/main/java/com/cloudbees/jenkins/support/filter/PrefilteredContent.java
- src/main/java/com/cloudbees/jenkins/support/filter/SensitiveContentFilter.java
- src/main/java/com/cloudbees/jenkins/support/impl/LogRecordContent.java
- src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
- src/main/java/com/cloudbees/jenkins/support/slowrequest/InflightRequest.java
- src/main/java/com/cloudbees/jenkins/support/slowrequest/SlowRequestChecker.java
- src/main/java/com/cloudbees/jenkins/support/timer/DeadlockTrackChecker.java
- src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
- src/test/java/com/cloudbees/jenkins/support/SupportTestUtils.java
- src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/NodeExecutorsTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/RunningBuildsTest.java
* Remove the use of `Optional<ContentFilter>` passed in parameters through the API. Use a `NoneFilter` implementation instead that simply pass through the value. This should simplify the readability, also avoid NPE and remove the need for null checks in some part of the code.
* Deprecated the existing methods `SupportPlugin#getContentFilter` / `SupportPlugin#getContentFilter(ensureLoaded)` in favor of `SupportPlugin#getDefaultContentFilter` / `SupportPlugin#getDefaultContentFilter(ensureLoaded)` and make sure that `ensureLoaded` also reloads the mappings.
* Deprecate `ContentFilter#ensureLoaded` that does not seem useful in favor of just using the existing `ContentFilter#reload`. 
* Also fixed checkstyle in the classes part of the fix
Tested on a test instance with thousands of items and …
> Use a passthrough filter if Anonymization disabled

- src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
This plugin's tests currently depend on `javax.inject`, preventing them from running against Jenkins core with Guice 7.0 or later which only provide `jakarta.inject` (currently Jenkins core ships Guice 6.0 which provides both `javax.inject` and `jakarta.jnject`). To prepare for this migration, stop using Guice in favor of traditional static dependency injection.
Ran `mvn clean verify -Dtest=com.cloudbees.jenkins.support.SupportActionTest` against https://github.com/jenkinsci/jenkins/pull/8889.
> Reduce usage of Guice

- src/main/java/com/cloudbees/jenkins/support/api/BaseFileContent.java
- src/test/java/com/cloudbees/jenkins/support/api/FileContentTest.java
https://github.com/jenkinsci/support-core-plugin/pull/502 had the side effect of normalizing line endings for all instances of `FileContent` even when anonymization is disabled, which makes it difficult to use support bundles to analyze issues where exact file contents are significant (e.g. build logs and associated metadata).
While looking at that issue, I _also_ noticed that any kind of `FileContent` that was detected as binary was actually written twice, once as binary and then once as text. Oops! From a quick look I think this has been broken since https://github.com/jenkinsci/support-core-plugin/pull/174.
```[tasklist]
```
> Preserve line endings in `FileContent` when anonymization is disabled and avoid duplicating binary content

- src/main/java/com/cloudbees/jenkins/support/filter/AdditionalFromFileStopWords.java
- src/main/java/com/cloudbees/jenkins/support/filter/AllAsciiCharactersStopWords.java
- src/main/java/com/cloudbees/jenkins/support/filter/AllowedOSNamesStopWords.java
- src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
- src/main/java/com/cloudbees/jenkins/support/filter/DefaultStopWords.java
- src/main/java/com/cloudbees/jenkins/support/filter/StopWords.java
Add an extension that allow plugins to add additional stop words. Which is useful for extension that produce filtered String / File contents that have words that should not be filtered.
I was also wondering if we should add the annotated `@Symbol` values to the list of stop words...
```[tasklist]
```
> Add ExtensionPoint to contribute to stop words

- pom.xml
Current Maven warns about this; in the future it might be fatal.
> Removing duplicate `dependency`

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
https://github.com/jenkinsci/support-core-plugin/runs/22561627825 is not reproducibe locally but has also been observed in PCT (@cloudbees reference BEE-10081). The failure does not make much sense because `AsyncResultCache.get` should always succeed on the built-in node (`Jenkins`). Locally:
```
FINER	c.c.j.support.AsyncResultCache#get: com.cloudbees.jenkins.support.impl.NetworkInterfaces$GetNetworkInterfaces@6ba48c4d on master succeeded
FINER	c.c.j.support.AsyncResultCache#get: com.cloudbees.jenkins.support.impl.NetworkInterfaces$GetNetworkInterfaces@35c553e2 on agent0 succeeded
```
> Trying to deflake `CheckFilterTest`

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
Split from https://github.com/jenkinsci/support-core-plugin/pull/522#discussion_r1521707377 due to prolonged discussion with @jtnord & @Dohbedoh.
> NPE in `AboutJenkins`

- src/main/java/com/cloudbees/jenkins/support/impl/AbstractItemDirectoryComponent.java
- src/main/java/com/cloudbees/jenkins/support/impl/RunDirectoryComponent.java
- src/main/resources/com/cloudbees/jenkins/support/impl/AbstractItemDirectoryComponent/help.html
- src/main/resources/com/cloudbees/jenkins/support/impl/DirectoryComponent/help-excludes.html
- src/main/resources/com/cloudbees/jenkins/support/impl/DirectoryComponent/help-includes.html
- src/main/resources/com/cloudbees/jenkins/support/impl/RunDirectoryComponent/help.html
- src/test/java/com/cloudbees/jenkins/support/impl/AbstractItemDirectoryComponentTest.java
- src/test/java/com/cloudbees/jenkins/support/impl/RunDirectoryComponentTest.java
* **Build Support** excludes needlessly looked in subdirectories for things like `stashes`.
* `artifacts` is not a directory name; it is `archive`. This particular important exclusion lacked test coverage. (Be careful not to mix up directory names with URL components, which are often subtly different: `archive` vs. `artifact`; `jobs` vs. `job`.)
* Default excludes were missing several kinds of directories that I have observed containing many (and often large) files in builds running on @cloudbees servers.
* **Project Support** excludes were mixing two sorts of entries: subitems; and standard excludes for builds. More clearly separate them and refine the patterns.
* Some help files displayed `{0}` which was apparently meant to be subtituted with something but was not.
* Links to Apache Ant …
> Fixes to `RunDirectoryComponent.excludes`

- pom.xml
- src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
Cleaning up from #517 since https://github.com/jenkinsci/jenkins/pull/9009 was accepted for backport to LTS.
> Deleting `Jenkins72799Hack`

- src/main/java/com/cloudbees/jenkins/support/api/ObjectComponent.java
This might seem like nitpicking, but I was puzzled for a bit going over this class, until I noticed it was most likely a copy paste of the javadoc of the parent `Component` class, which is the actual unit of user consent.
> [doc] Remove misleading javadoc comment

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
While in general the project to move Jenkins onto EE 9 will maintain full compatibility with EE 8 (including the introduction of EE 9 `StaplerRequest2` and `StaplerResponse2` APIs), creating an EE 9 `Stapler2` class is overkill, since almost nothing outside of Stapler and Jenkins core calls `Stapler` methods other than `Stapler#getCurrentRequest` and `Stapler#getCurrentResponse`, both of which we can deprecate in favor of `Stapler#getCurrentRequest2` and `Stapler#getCurrentResponse2` (thus preserving compatibility for those two important methods but otherwise migrating the entire class to EE 9 without the maintainence burden of retaining a separate EE 8 version of the class). The only exception I found was this plugin, which called a few methods on the underlying `HttpServlet`, which will …
> Forward compatibility with EE 9

- src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
Was probably introduced by https://github.com/jenkinsci/support-core-plugin/pull/338.
Propose to load the recorders after CasC init (see https://github.com/jenkinsci/configuration-as-code-plugin/blob/1810.v9b_c30a_249a_4c/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L337). 
I thought about just always targeting the reference `Jenkins.get().getLog().getRecorders()` from [CustomHandler#publish](https://github.com/jenkinsci/support-core-plugin/blob/1459.va_f527ce9a_d64/src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java#L166) but wonder if that would be overkill ? We go through this for every log record.. cc @jglick I wonder WDYT about this ?
* Start Jenkins with CasC:
```
jenkins:
log:
recorders:
- loggers:
- level: "ALL"
name: …
```
> [JENKINS-73402] Load LogManager recorder afetr CasC loading

- src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
- src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
Reverting most of #271 since it is obsolete as of https://github.com/jenkinsci/jenkins/pull/8762.
> Removing `JNLPLauncher.webSocket` notation in `nodes.md`

- src/main/java/com/cloudbees/jenkins/support/impl/UpdateCenter.java
- src/test/java/com/cloudbees/jenkins/support/impl/UpdateCenterTest.java
Recently discovered that wildcard syntax including several `*` are mis-interpreted by Markdown parsers.. For example `10.1.*.*` would be `10.1..` with a bold dot..
> Fix Markdown syntax of Non proxy hosts and Proxy host

- src/main/java/com/cloudbees/jenkins/support/impl/TaskLogs.java
At least until https://github.com/jenkinsci/jenkins/pull/9663 is widely deployed.
> [JENKINS-73692] Ignore `Periodic background build discarder.log`

- src/main/java/com/cloudbees/jenkins/support/filter/DefaultStopWords.java
If an instance contains jobs named "up" and/or "running", those end up being anonymized, leading to a log entry like: `Jenkins is fully item_outer_pub and item_square_life`.
This is not really convenient when browsing through the logs and looking for "up and running".
With this change, the log entry becomes `Jenkins is up and running`.
More generally, and outside of the context of this PR, I wonder if some groups of words should not be automatically excluded, like two letter words, adverbs etc...
> [chore] Add "up" and "running" as stop words

- README.md
- src/main/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponent.java
- src/test/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponentTest.java
- src/test/resources/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponentTest/regexpFromFileFilter/support/other-config-files-filters.txt
Add ability to provide more filters to the `OtherConfigFilesComponent` if some `xml` files are meant to be excluded in extensions and plugins.
> Add ability to filter more Config Files from OtherConfigFilesComponent

- src/main/java/com/cloudbees/jenkins/support/api/LaunchLogsFileContent.java
- src/main/java/com/cloudbees/jenkins/support/filter/FilteredInputStream.java
- src/test/java/com/cloudbees/jenkins/support/filter/FilteredInputStreamTest.java
I was made aware of an case where `LaunchLogsFileContent` was loading the entire agent launch log file into memory. More efficient to read at most one line at a time into memory, allowing the other lines to be garbage-collected.
`mvn clean verify`, new unit test
> JENKINS-73984: More efficient filtering of input streams

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/api/Component.java
- src/test/java/com/cloudbees/jenkins/support/SupportPluginTest.java
Added a way for components to supersede other components in the support bundle creation process
> API to supersede components if not required

- src/test/java/com/cloudbees/jenkins/support/impl/NodeExecutorsTest.java
Adapt to https://github.com/jenkinsci/workflow-job-plugin/pull/499.
> Relax assertion in `NodeExecutorsTest`

- src/main/java/com/cloudbees/jenkins/support/configfiles/AgentsConfigFile.java
Apparently a regression in #198:
```
WARNING	c.c.j.support.SupportPlugin#appendManifestContents: Could not get content from Agent Configuration File for support bundle
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:233)
at PluginClassLoader for support-core//com.cloudbees.jenkins.support.configfiles.AgentsConfigFile.lambda$addContents$0(AgentsConfigFile.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at PluginClassLoader for support-core//com.cloudbees.jenkins.support.configfiles.AgentsConfigFile.addContents(AgentsConfigFile.java:87)
at PluginClassLoader for support-core//com.cloudbees.jenkins.support.SupportPlugin$1.visit(SupportPlugin.java:358)
at PluginClassLoader for …
```
> NPE in `AgentsConfigFile.addContents`

- src/main/java/com/cloudbees/jenkins/support/SupportAction.java
- src/main/java/com/cloudbees/jenkins/support/SupportCommand.java
- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
- src/main/java/com/cloudbees/jenkins/support/actions/SupportObjectAction.java
- src/main/java/com/cloudbees/jenkins/support/impl/AboutUser.java
- src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
Reviewing #617, I was alarmed to find that this plugin defaults to impersonating `SYSTEM` during interactive bundle generation, and (as of the old a6de1be6ea1e3b77ea7bbb6c6893745fbf1d11ce) relies on the author of a `Component` to actually check the requester’s authentication where applicable. This goes against the principle of least surprise and safety by default. In fact most components require `ADMINISTER` anyway (the option to do otherwise dates all the way back to 066bd8d33a88b7866b23c20f66ec56313f57924e), but not all. I could not find any actually problematic cases, but for example https://github.com/jenkinsci/support-core-plugin/blob/3435ec4057ae19e04dee06d2eba8c5f1128e603e/src/main/java/com/cloudbees/jenkins/support/impl/ItemsContent.java#L87 is uncomfortable because it is …
> Removing `requesterAuthentication`

- src/main/java/com/cloudbees/jenkins/support/impl/RootCAs.java
When troubleshooting PKIX issues, it is important to know the source of the Trust Manager in addition to its contents. Therefore, print basic file information about typical trust store locations.
I jotted this down as I was think of how to improve data for troubleshooting PKIX issues.
> Print basic file information about trust store locations

- src/main/java/com/cloudbees/jenkins/support/filter/DefaultStopWords.java
- src/main/java/com/cloudbees/jenkins/support/filter/PluginsStopWords.java
Adding more stop words after looking at a recent anonymized bundle, and also terms from installed plugin names.
> Added plugin name terms and more common terms to stop words

- src/main/java/com/cloudbees/jenkins/support/api/BaseFileContent.java
- src/main/java/com/cloudbees/jenkins/support/api/FileContent.java
- src/main/java/com/cloudbees/jenkins/support/api/UnfilteredFileContent.java
Noticed in a support bundle several exceptions of the form
```
WARNING	c.c.j.s.a.UnfilteredFileContent#lambda$createBaseFileContent$0: Error opening file /var/jenkins_home/slow-requests/20250424-134904.013.txt
java.io.FileNotFoundException: /var/jenkins_home/slow-requests/20250424-134904.013.txt (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at PluginClassLoader for support-core//com.cloudbees.jenkins.support.api.UnfilteredFileContent.getInputStream(UnfilteredFileContent.java:85)
at PluginClassLoader for support-core//com.cloudbees.jenkins.support.api.UnfilteredFileContent.lambda$createBaseFileContent$0(UnfilteredFi …
```
> [JENKINS-64261] BaseFileContent.InputStreamSupplier

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
In case no async component is selected while generating a new bundle, the following stack appears in the logs:
```
2025-04-25 13:50:46.324+0000 [id=91]	WARNING	c.c.j.support.SupportPlugin#writeBundle: Error while processing sync components in async mode
java.io.FileNotFoundException: /var/folders/jl/z9cm5_452pv9hbm1k6pr0fyc0000gn/T/support-bundle/6faf6b7f-08f4-4414-b8c0-7fc19d49922e/support-bundle.zip (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at PluginClassLoader for support-core//com.cloudbees.jenkins.support.SupportPlugin.writeBundle(SupportPlugin.java:522)
at PluginClassLoader for …
```
> [bug] Ensure a sync component archive exists before using it

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
[JENKINS-75968](https://issues.jenkins.io/browse/JENKINS-75968)
The system property `com.cloudbees.jenkins.support.SupportPlugin.MAX_JENKINS_LOG_ENTRIES_PER_FILE` can now be set to tune the amount of log records to have before log rollover.
deployed to an instance start as `java  -Dcom.cloudbees.jenkins.support.SupportPlugin.MAX_LOG_ENTRIES_PER_FILE=10 -jar jenkins.war --httpListenAddress=127.0.0.2` 
validated that the files are really small (they contain 11 log entries as there is an off by one in the existing code that I am not intending to fix).
> [JENKINS-75968] allow the tuning of the number of Jenkins logs caputred

- src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
my developer testing had a typo in the system property name that matched the property. (trailing space).
Fix the property by removing the (unusual) trailing space
> Fix system property for max jenkins logs

- src/main/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitors.java
- src/test/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitorsTest.java
Example:
----
Monitors
========
`hudson.diagnosis.TooManyJobsButNoView` _Too Many Jobs Not Organized in Views_
--------------
(active and enabled)
`hudson.model.UpdateCenter$CoreUpdateMonitor` _Jenkins Update Notification_
--------------
(active and enabled)
`jenkins.diagnostics.URICheckEncodingMonitor` _Check URI Encoding_
--------------
(active and enabled)
`jenkins.security.UpdateSiteWarningsMonitor` _Update Site Warnings_
--------------
(active and enabled)
> Show `AdministrativeMonitor.displayName`
